/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_MyApplication__data.c
 *
 * Description  : Source-File for MBDS model APP_MyApplication_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.253
 *                Created by       : Udo Kaiser (uidf0608) on Thu Apr 23 04:11:25 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_MyApplication_.h"
#include "APP_MyApplication__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Invariant block signals (default storage) */
const ConstB_APP_MyApplication_ APP_MyApplication__ConstB =
{
  18000U,                              /* '<S275>/Product1' */
  53U,                                 /* '<S290>/Subtract' */
  1U,                                  /* '<S290>/Math Function' */
  53U,                                 /* '<S273>/Subtract' */
  1U,                                  /* '<S273>/Math Function' */
  2700U,                               /* '<S276>/Product' */
  2021U,                               /* '<S264>/Switch1' */
  2021U,                               /* '<S264>/Switch' */
  51U,                                 /* '<S279>/Add' */
  18615U,                              /* '<S279>/Product' */
  53U,                                 /* '<S279>/Subtract' */
  13U,                                 /* '<S279>/Divide' */
  18628U,                              /* '<S279>/Add1' */
  53U,                                 /* '<S280>/Subtract' */
  1U,                                  /* '<S280>/Math Function' */
  12U,                                 /* '<S284>/Switch2' */
  11U,                                 /* '<S284>/Subtract' */
  31U,                                 /* '<S284>/Selector' */
  12U,                                 /* '<S267>/Switch2' */
  11U,                                 /* '<S267>/Subtract' */
  31U,                                 /* '<S267>/Selector' */
  55U,                                 /* '<S264>/Switch1' */
  55U,                                 /* '<S264>/Switch' */
  45U,                                 /* '<S264>/Switch1' */
  45U,                                 /* '<S264>/Switch' */
  5U,                                  /* '<S264>/Switch1' */
  5U,                                  /* '<S264>/Switch' */
  1U,                                  /* '<S264>/Switch1' */
  1U,                                  /* '<S264>/Switch' */
  0U,                                  /* '<S277>/Subtract4' */
  12U,                                 /* '<S264>/Switch1' */
  12U,                                 /* '<S264>/Switch' */
  1U,                                  /* '<S207>/Width' */
  1,                                   /* '<S287>/Relational Operator6' */
  1,                                   /* '<S287>/Relational Operator7' */
  1,                                   /* '<S287>/Logical Operator' */
  1,                                   /* '<S284>/Relational Operator4' */
  0,                                   /* '<S290>/Relational Operator1' */
  0,                                   /* '<S290>/Relational Operator' */
  1,                                   /* '<S290>/Data Type Conversion1' */
  0,                                   /* '<S290>/Logical Operator1' */
  0,                                   /* '<S290>/Logical Operator' */
  1,                                   /* '<S284>/Logical Operator3' */
  1,                                   /* '<S284>/Relational Operator8' */
  1,                                   /* '<S284>/Logical Operator1' */
  1,                                   /* '<S285>/Relational Operator3' */
  1,                                   /* '<S289>/Relational Operator' */
  1,                                   /* '<S289>/Relational Operator1' */
  1,                                   /* '<S270>/Relational Operator6' */
  1,                                   /* '<S270>/Relational Operator7' */
  1,                                   /* '<S270>/Logical Operator' */
  1,                                   /* '<S267>/Relational Operator4' */
  0,                                   /* '<S273>/Relational Operator1' */
  0,                                   /* '<S273>/Relational Operator' */
  1,                                   /* '<S273>/Data Type Conversion1' */
  0,                                   /* '<S273>/Logical Operator1' */
  0,                                   /* '<S273>/Logical Operator' */
  1,                                   /* '<S267>/Logical Operator3' */
  1,                                   /* '<S267>/Relational Operator8' */
  1,                                   /* '<S267>/Logical Operator1' */
  1,                                   /* '<S271>/Relational Operator' */
  1,                                   /* '<S269>/Relational Operator2' */
  1,                                   /* '<S268>/Relational Operator3' */
  1,                                   /* '<S272>/Relational Operator' */
  1,                                   /* '<S264>/Logical Operator1' */
  1,                                   /* '<S272>/Relational Operator1' */
  0,                                   /* '<S280>/Relational Operator1' */
  0,                                   /* '<S280>/Relational Operator3' */
  0,                                   /* '<S280>/Logical Operator' */

  /* Start of '<S146>/LoopOverBits' */
  {
    1U,                                /* '<S210>/Width' */
    1                                  /* '<S210>/DataType' */
  }
  ,

  /* End of '<S146>/LoopOverBits' */

  /* Start of '<S145>/LoopOverBits' */
  {
    1U,                                /* '<S209>/Width' */
    1                                  /* '<S209>/DataType' */
  }
  ,

  /* End of '<S145>/LoopOverBits' */

  /* Start of '<S144>/LoopOverBits' */
  {
    1U,                                /* '<S208>/Width' */
    1                                  /* '<S208>/DataType' */
  }
  ,

  /* End of '<S144>/LoopOverBits' */

  /* Start of '<S142>/LoopOverBits' */
  {
    1U,                                /* '<S206>/Width' */
    1                                  /* '<S206>/DataType' */
  }
  ,

  /* End of '<S142>/LoopOverBits' */

  /* Start of '<S141>/LoopOverBits' */
  {
    1U,                                /* '<S205>/Width' */
    1                                  /* '<S205>/DataType' */
  }
  ,

  /* End of '<S141>/LoopOverBits' */

  /* Start of '<S140>/LoopOverBits' */
  {
    1U,                                /* '<S204>/Width' */
    0                                  /* '<S204>/DataType' */
  }
  /* End of '<S140>/LoopOverBits' */
};

/* Constant parameters (default storage) */
const ConstP_APP_MyApplication_ APP_MyApplication__ConstP =
{
  /* Pooled Parameter (Expression: )
   * Referenced by:
   *   '<S190>/Constant1'
   *   '<S301>/Constant1'
   */
  {
    0U, 31U, 28U, 31U, 30U, 31U, 30U, 31U, 31U, 30U, 31U, 30U, 31U
  },

  /* Pooled Parameter (Expression: )
   * Referenced by:
   *   '<S278>/Constant1'
   *   '<S295>/Constant1'
   */
  {
    0U, 31U, 28U, 31U, 30U, 31U, 30U, 31U, 31U, 30U, 31U, 30U
  }
};

/***************************************************************************
 * EOF: APP_MyApplication__data.c
 ***************************************************************************/
