@echo off
SET MATLAB=C:\LegacyApp\MATLAB_R2018b
SET Path=C:\Program Files\MBDS_v0820\MBRT\eBSG_EVO_MASTER\Host\GreenHills;%Path%
"%MATLAB%\bin\win64\gmake" -f SYS_BSG_2023_New.mk _MBDS_DIR="C:\Program Files\MBDS_v0820" _PROJECT_DIR="D:\SDBox_MAN_Master_Expansion\Master_ICPrime\BSG_2023_MASTER" _PROJECT_NAME=BSG_2023_New _RESOURCETYPE=eBSG_EVO_MASTER _ADMINHEADERTYPE="Admin Header 3.0" _SW_STARTADDRESS=0x1A20000 _SW_ENDADDRESS=0x1DCFFFF _TASK_INDEX=0 _OUTPUTMODE=Binary _DEBUGMODE=On _GENERATE_A2L=On _GENERATE_ODX=On
