/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_IOControl__private.h
 *
 * Description  : Header file for MBDS model APP_IOControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.2
 *                Created by       : Marcio Kopke (uid96494) on Tue Dec 22 10:16:48 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_IOControl__private_h_
#define RTW_HEADER_APP_IOControl__private_h_
#include "rtwtypes.h"
#include "APP_IOControl_.h"

/* Includes for objects with custom storage classes. */
#include "ks32_io.h"

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/
extern void APP_IOControl__a4(uint16_T rtu_u, const uint8_T rtu_SEL[2], const
  ConstB_LoopOverBits_APP_IOContr *localC, DW_LoopOverBits_APP_IOControl_
  *localDW);
extern void APP_IOControl__nn(DW_OutCtrl_APP_IOControl_ *localDW);
extern void APP_IOControl__g1y(boolean_T rtu_bo_OutRqst, boolean_T
  rtu_bo_FailDetect, DW_OutCtrl_APP_IOControl_ *localDW);
extern void APP_IOControl__js(DW_TrailerDetection_APP_IOContr *localDW);
extern void APP_IOControl__o0(boolean_T rtu_bo_OutRqst, uint8_T rtu_u8_TdTimeout,
  DW_TrailerDetection_APP_IOContr *localDW);
extern void APP_IOControl__fg(DW_TrailerDetection_APP_IOCo_gm *localDW);
extern void APP_IOControl__cx(boolean_T rtu_bo_OutRqst, uint8_T rtu_u8_TdTimeout,
  DW_TrailerDetection_APP_IOCo_gm *localDW);

#endif                                 /* RTW_HEADER_APP_IOControl__private_h_ */

/***************************************************************************
 * EOF: APP_IOControl__private.h
 ***************************************************************************/
