/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_DevicesControl_.c
 *
 * Description  : Source-File for MBDS model APP_DevicesControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.6
 *                Created by       : Marcio Kopke (uid96494) on Wed Dec 30 09:35:41 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_DevicesControl_.h"
#include "APP_DevicesControl__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Model step function */
void APP_DevicesControl__step(void)
{
  uint8_T rtb_DataTypeConversion2_c4;
  uint8_T rtb_ShiftArithmetic1;
  uint32_T tmp;
  uint16_T tmp_0;

  /* DataStoreWrite: '<S104>/DataStoreMemory' incorporates:
   *  Constant: '<S5>/Constant'
   */
  OUT_TSUD_DeviceEnable_001297 = true;

  /* DataStoreWrite: '<S105>/DataStoreMemory' incorporates:
   *  Constant: '<S5>/Constant1'
   */
  OUT_TSUD_SetDiagWriteOdoResponse_001304 = 0U;

  /* DataStoreWrite: '<S101>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S94>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Tsu_TSU_Sts_Speed_Shaft_DIAG_001803 =
    DIAG_TSUD_ShaftSpeed_DIAG_001301;

  /* DataStoreWrite: '<S103>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S95>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Tsu_TSU_Sts_Speed_Vehicle_DIAG_001801 =
    DIAG_TSUD_VehicleSpeed_DIAG_001303;

  /* DataStoreWrite: '<S99>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S96>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Tsu_TSU_Sts_MessageEnable_001805 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S100>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S97>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Tsu_TSU_Sts_Speed_Shaft_001804 = IN_TSUD_ShaftSpeed_001300;

  /* DataStoreWrite: '<S102>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S98>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Tsu_TSU_Sts_Speed_Vehicle_001802 = IN_TSUD_VehicleSpeed_001302;

  /* Logic: '<S15>/Operator' incorporates:
   *  Constant: '<S3>/Constant'
   *  DataStoreRead: '<S27>/DataStoreMemory'
   *  DataStoreRead: '<S28>/DataStoreMemory'
   *  DataStoreWrite: '<S32>/DataStoreMemory'
   *  RelationalOperator: '<S16>/Operator'
   */
  OUT_DateandTime_SetTime_001321 = ((((int32_T)
    IN_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_MessageState_001713) == 0) &&
    (IN_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_DateTime_SetTime_001678));

  /* DataTypeConversion: '<S3>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S24>/DataStoreMemory'
   *  DataStoreWrite: '<S29>/DataStoreMemory'
   */
  OUT_DateandTime_HourOffset_001316 = (int8_T)
    IN_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_DateTime_HourOffs_001681;

  /* DataTypeConversion: '<S3>/Data Type Conversion1' incorporates:
   *  DataStoreRead: '<S25>/DataStoreMemory'
   *  DataStoreWrite: '<S30>/DataStoreMemory'
   */
  OUT_DateandTime_MinuteOffset_001319 = (int8_T)
    IN_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_DateTime_MinuteOf_001680;

  /* DataStoreWrite: '<S34>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S17>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_LocalTime_Sts_DateTime_DIAG_001806 =
    DIAG_DateandTime_LocalTime_DIAG_001318;

  /* DataStoreWrite: '<S37>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S18>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_SetTime_Sts_DateTime_DIAG_001808 =
    DIAG_DateandTime_SetTime_DIAG_001322;

  /* DataStoreWrite: '<S39>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S19>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_SystemTime_Sts_DateTime_DIAG_001810 =
    DIAG_DateandTime_SystemTime_DIAG_001324;

  /* DataStoreWrite: '<S33>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S20>/DataStoreMemory'
   */
  OUT_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_MessageEnable_001712 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S36>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S20>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_LocalTime_Sts_MessageEnable_001813 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S38>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S20>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_SetTime_Sts_MessageEnable_001814 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S41>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S20>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_SystemTime_Sts_MessageEnable_001815 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S43>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S20>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_TicksCount_Sts_MessageEnable_001816 =
    INOUT_RAMDevice_boSystemWake_000003;

  /* DataStoreWrite: '<S35>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S21>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_LocalTime_Sts_DateTime_LocalT_001807 =
    IN_DateandTime_LocalTime_001317;

  /* DataStoreWrite: '<S40>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S22>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_SystemTime_Sts_DateTime_Syste_001809 =
    IN_DateandTime_SystemTime_001323;

  /* DataStoreWrite: '<S42>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S23>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Date_DateTime_TicksCount_Sts_DateTime_Ticks_001811 =
    IN_DateandTime_TicksCount_001325;

  /* DataStoreWrite: '<S31>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S26>/DataStoreMemory'
   */
  OUT_DateandTime_NewSystemTime_001320 =
    IN_PCAN_Rx_Ctrl_DateTime_SetTime_Ctrl_DateTime_NewSyste_001679;

  /* DataTypeConversion: '<S4>/Data Type Conversion2' incorporates:
   *  DataStoreRead: '<S46>/DataStoreMemory'
   *  S-Function (sfix_bitop): '<S44>/Operator'
   */
  rtb_DataTypeConversion2_c4 = (uint8_T)(IN_AnalogInputsPWR_IN_PWR_000721 & 255U);

  /* DataTypeConversion: '<S4>/Data Type Conversion3' incorporates:
   *  ArithShift: '<S4>/Shift Arithmetic'
   *  DataStoreRead: '<S46>/DataStoreMemory'
   *  DataTypeConversion: '<S45>/DataType'
   *  S-Function (sfix_bitop): '<S45>/Operator'
   */
  rtb_ShiftArithmetic1 = (uint8_T)((real32_T)ldexp((real_T)((real32_T)((int32_T)
    ((int32_T)(((int32_T)IN_AnalogInputsPWR_IN_PWR_000721) & 65280)))), -8));

  /* DataStoreWrite: '<S81>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant7'
   *  DataStoreRead: '<S47>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion4'
   */
  OUT_LinSlave_SetFrameLss1B_002326[0] = (uint8_T)
    (IN_DigitalInputs_IN_DIG_36_000060 ? ((uint8_T)1) : ((uint8_T)0));
  OUT_LinSlave_SetFrameLss1B_002326[1] = rtb_DataTypeConversion2_c4;
  OUT_LinSlave_SetFrameLss1B_002326[2] = rtb_ShiftArithmetic1;
  OUT_LinSlave_SetFrameLss1B_002326[3] = 0U;

  /* DataStoreWrite: '<S82>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant7'
   *  DataStoreRead: '<S47>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion4'
   */
  OUT_LinSlave_SetFrameMlfB_002327[0] = (uint8_T)
    (IN_DigitalInputs_IN_DIG_36_000060 ? ((uint8_T)1) : ((uint8_T)0));
  OUT_LinSlave_SetFrameMlfB_002327[1] = rtb_DataTypeConversion2_c4;
  OUT_LinSlave_SetFrameMlfB_002327[2] = rtb_ShiftArithmetic1;
  OUT_LinSlave_SetFrameMlfB_002327[3] = 0U;

  /* DataTypeConversion: '<S4>/Data Type Conversion1' incorporates:
   *  DataStoreRead: '<S46>/DataStoreMemory'
   *  DataStoreWrite: '<S87>/DataStoreMemory'
   */
  tmp = IN_AnalogInputsPWR_IN_PWR_000721;
  if (IN_AnalogInputsPWR_IN_PWR_000721 > 65535U)
  {
    tmp = 65535U;
  }

  OUT_Tester_1_BSG_STATUS_BatteryVoltage_001395 = (uint16_T)tmp;

  /* End of DataTypeConversion: '<S4>/Data Type Conversion1' */

  /* DataTypeConversion: '<S4>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S47>/DataStoreMemory'
   *  DataStoreWrite: '<S88>/DataStoreMemory'
   */
  OUT_Tester_1_BSG_STATUS_Button_KL15_001389 = (uint8_T)
    (IN_DigitalInputs_IN_DIG_36_000060 ? ((uint8_T)1) : ((uint8_T)0));

  /* Sum: '<S4>/Add' incorporates:
   *  ArithShift: '<S4>/Shift Arithmetic1'
   *  DataStoreRead: '<S60>/DataStoreMemory'
   *  DataStoreRead: '<S76>/DataStoreMemory'
   *  DataStoreRead: '<S77>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion5'
   *  Product: '<S4>/Product8'
   */
  tmp = (((uint32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_ErrorType_001359) +
         ((uint32_T)((uint8_T)
                     (IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_ErrorLoc_001360 <<
                      ((uint64_T)4))))) + ((uint32_T)(((uint32_T)
    IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn1_001361) << ((uint64_T)8)));
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product1' incorporates:
   *  DataStoreRead: '<S62>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion6'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn2_001362) > 127)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn2_001362) << ((uint64_T)9)));
  }

  /* End of Product: '<S4>/Product1' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product2' incorporates:
   *  DataStoreRead: '<S63>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion7'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn3_001363) > 63)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn3_001363) << ((uint64_T)10)));
  }

  /* End of Product: '<S4>/Product2' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product3' incorporates:
   *  DataStoreRead: '<S66>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion8'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn4_001364) > 31)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn4_001364) << ((uint64_T)11)));
  }

  /* End of Product: '<S4>/Product3' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product4' incorporates:
   *  DataStoreRead: '<S69>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion9'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn5_001365) > 15)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn5_001365) << ((uint64_T)12)));
  }

  /* End of Product: '<S4>/Product4' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product5' incorporates:
   *  DataStoreRead: '<S72>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion10'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn6_001366) > 7)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn6_001366) << ((uint64_T)13)));
  }

  /* End of Product: '<S4>/Product5' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product6' incorporates:
   *  DataStoreRead: '<S73>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion11'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn7_001367) > 3)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn7_001367) << ((uint64_T)14)));
  }

  /* End of Product: '<S4>/Product6' */

  /* Sum: '<S4>/Add' */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  /* Product: '<S4>/Product7' incorporates:
   *  DataStoreRead: '<S74>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion12'
   */
  if (((int32_T)IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn8_001368) > 1)
  {
    tmp_0 = MAX_uint16_T;
  }
  else
  {
    tmp_0 = (uint16_T)((uint32_T)(((uint32_T)
      IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_Btn8_001368) << ((uint64_T)15)));
  }

  /* End of Product: '<S4>/Product7' */

  /* Sum: '<S4>/Add' incorporates:
   *  DataStoreWrite: '<S84>/DataStoreMemory'
   */
  tmp += (uint32_T)tmp_0;
  if (tmp > 65535U)
  {
    tmp = 65535U;
  }

  OUT_PCAN_Tx_Acc_Lin_Sts_BatteryVoltage_001647 = (uint16_T)tmp;

  /* DataStoreWrite: '<S90>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_Tester_1_BSG_STATUS_Voltage_OV1_001391 = 0U;

  /* DataStoreWrite: '<S91>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_Tester_1_BSG_STATUS_Voltage_OV2_001392 = 0U;

  /* DataStoreWrite: '<S92>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_Tester_1_BSG_STATUS_Voltage_UV1_001393 = 0U;

  /* DataStoreWrite: '<S93>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_Tester_1_BSG_STATUS_Voltage_UV2_001394 = 0U;

  /* DataStoreWrite: '<S89>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant1'
   */
  OUT_Tester_1_BSG_STATUS_Voltage_Normal_001390 = 1U;

  /* DataStoreWrite: '<S86>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant14'
   */
  OUT_PCAN_Tx_Acc_Lin_Sts_MessageEnable_001677 = true;

  /* DataStoreWrite: '<S79>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant2'
   */
  OUT_LIN_01_LinNetworkRequest1_001396 = true;

  /* DataStoreWrite: '<S80>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant3'
   */
  OUT_LIN_01_ScheduleTable_001397 = 1U;

  /* DataStoreWrite: '<S83>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant4'
   */
  OUT_LinSlave_WakeupRequest_002328 = false;

  /* DataTypeConversion: '<S4>/Data Type Conversion13' incorporates:
   *  DataStoreRead: '<S78>/DataStoreMemory'
   *  DataStoreWrite: '<S85>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Acc_Lin_Sts_Button_KL15_001648 = (((int32_T)
    IN_NodeMFL_MFL_BtnInfo_MFL_BtnInfo_MsgCounter_001358) != 0);

  /* DataStoreWrite: '<S10>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_InertianSensor_Accelerometer_DeviceEnable_002135 = true;

  /* DataTypeConversion: '<S2>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S7>/DataStoreMemory'
   *  DataStoreWrite: '<S12>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Acc_ACCELEROMETER_X_002131 = (uint16_T)
    IN_InertianSensor_Accelerometer_Ax_002138;

  /* DataTypeConversion: '<S2>/Data Type Conversion1' incorporates:
   *  DataStoreRead: '<S8>/DataStoreMemory'
   *  DataStoreWrite: '<S13>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Acc_ACCELEROMETER_Y_002132 = (uint16_T)
    IN_InertianSensor_Accelerometer_Ay_002137;

  /* DataTypeConversion: '<S2>/Data Type Conversion2' incorporates:
   *  DataStoreRead: '<S9>/DataStoreMemory'
   *  DataStoreWrite: '<S14>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Acc_ACCELEROMETER_Z_002133 = (uint16_T)
    IN_InertianSensor_Accelerometer_Az_002136;

  /* DataStoreWrite: '<S11>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S6>/DataStoreMemory'
   */
  OUT_PCAN_Tx_Acc_ACCELEROMETER_MessageEnable_002134 =
    INOUT_RAMDevice_boSystemWake_000003;
}

/* Model initialize function */
void APP_DevicesControl__initialize(void)
{
  /* (no initialization code required) */
}

/***************************************************************************
 * EOF: APP_DevicesControl_.c
 ***************************************************************************/
