/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_DevicesControl_.h
 *
 * Description  : Header file for MBDS model APP_DevicesControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.6
 *                Created by       : Marcio Kopke (uid96494) on Wed Dec 30 09:35:41 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_DevicesControl__h_
#define RTW_HEADER_APP_DevicesControl__h_
#include <math.h>
#ifndef APP_DevicesControl__COMMON_INCLUDES_
# define APP_DevicesControl__COMMON_INCLUDES_
#define __TMWTYPES__                                             /* Inferred types compatibility mode */
#include "rtwtypes.h"
#endif                                 /* APP_DevicesControl__COMMON_INCLUDES_ */

#include "APP_DevicesControl__types.h"

/* Macros for accessing real-time model data structure */

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/

/* Model entry point functions */
extern void APP_DevicesControl__initialize(void);
extern void APP_DevicesControl__step(void);

/*-
 * These blocks were eliminated from the model due to optimizations:
 *
 * Block '<S15>/DataType' : Eliminate redundant data type conversion
 * Block '<S44>/DataType' : Eliminate redundant data type conversion
 */

/*-
 * The generated code includes comments that allow you to trace directly
 * back to the appropriate location in the model.  The basic format
 * is <system>/block_name, where system is the system number (uniquely
 * assigned by Simulink) and block_name is the name of the block.
 *
 * Note that this particular code originates from a subsystem build,
 * and has its own system numbers different from the parent model.
 * Refer to the system hierarchy for this subsystem below, and use the
 * MATLAB hilite_system command to trace the generated code back
 * to the parent model.  For example,
 *
 * hilite_system('APP_DevicesControl/Model/APP_DevicesControl_')    - opens subsystem APP_DevicesControl/Model/APP_DevicesControl_
 * hilite_system('APP_DevicesControl/Model/APP_DevicesControl_/Kp') - opens and selects block Kp
 *
 * Here is the system hierarchy for this model
 *
 * '<Root>' : 'APP_DevicesControl/Model'
 * '<S1>'   : 'APP_DevicesControl/Model/APP_DevicesControl_'
 * '<S2>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer'
 * '<S3>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime'
 * '<S4>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl'
 * '<S5>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl'
 * '<S6>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/in_INOUT_RAMDevice.boSystemWake'
 * '<S7>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/in_IN_InertianSensor.Accelerometer.Ax'
 * '<S8>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/in_IN_InertianSensor.Accelerometer.Ay'
 * '<S9>'   : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/in_IN_InertianSensor.Accelerometer.Az'
 * '<S10>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/out_OUT_InertianSensor.Accelerometer.DeviceEnable'
 * '<S11>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/out_OUT_PCAN.Tx_Acc.ACCELEROMETER.MessageEnable'
 * '<S12>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/out_OUT_PCAN.Tx_Acc.ACCELEROMETER.X'
 * '<S13>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/out_OUT_PCAN.Tx_Acc.ACCELEROMETER.Y'
 * '<S14>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_Accelerometer/out_OUT_PCAN.Tx_Acc.ACCELEROMETER.Z'
 * '<S15>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/AND'
 * '<S16>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/EQ'
 * '<S17>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_DIAG_DateandTime.LocalTime_DIAG'
 * '<S18>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_DIAG_DateandTime.SetTime_DIAG'
 * '<S19>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_DIAG_DateandTime.SystemTime_DIAG'
 * '<S20>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_INOUT_RAMDevice.boSystemWake'
 * '<S21>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_DateandTime.LocalTime'
 * '<S22>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_DateandTime.SystemTime'
 * '<S23>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_DateandTime.TicksCount'
 * '<S24>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.DateTime_HourOffset'
 * '<S25>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.DateTime_MinuteOffset'
 * '<S26>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.DateTime_NewSystemTime'
 * '<S27>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.DateTime_SetTime'
 * '<S28>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/in_IN_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.MessageState'
 * '<S29>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_DateandTime.HourOffset'
 * '<S30>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_DateandTime.MinuteOffset'
 * '<S31>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_DateandTime.NewSystemTime'
 * '<S32>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_DateandTime.SetTime'
 * '<S33>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Rx_Ctrl.DateTime_SetTime_Ctrl.MessageEnable'
 * '<S34>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_LocalTime_Sts.DateTime_DIAG'
 * '<S35>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_LocalTime_Sts.DateTime_LocalTime'
 * '<S36>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_LocalTime_Sts.MessageEnable'
 * '<S37>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_SetTime_Sts.DateTime_DIAG'
 * '<S38>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_SetTime_Sts.MessageEnable'
 * '<S39>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_SystemTime_Sts.DateTime_DIAG'
 * '<S40>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_SystemTime_Sts.DateTime_SystemTime'
 * '<S41>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_SystemTime_Sts.MessageEnable'
 * '<S42>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_TicksCount_Sts.DateTime_TicksCount'
 * '<S43>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_DateTime/out_OUT_PCAN.Tx_Date.DateTime_TicksCount_Sts.MessageEnable'
 * '<S44>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/AND1'
 * '<S45>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/AND2'
 * '<S46>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_AnalogInputsPWR.IN_PWR'
 * '<S47>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_DigitalInputs.IN_DIG_36'
 * '<S48>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_LinSlave.DeviceState'
 * '<S49>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_D1'
 * '<S50>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_D4'
 * '<S51>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_D7'
 * '<S52>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_DM'
 * '<S53>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_MsgCounter'
 * '<S54>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_N'
 * '<S55>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_R1'
 * '<S56>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_RM'
 * '<S57>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DNR_Position_SwitchStatus'
 * '<S58>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeDNR.DNR_Position.DeviceState'
 * '<S59>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.DeviceState'
 * '<S60>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn1'
 * '<S61>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn10'
 * '<S62>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn2'
 * '<S63>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn3'
 * '<S64>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn3LPress'
 * '<S65>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn3SPress'
 * '<S66>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn4'
 * '<S67>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn4LPress'
 * '<S68>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn4SPress'
 * '<S69>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn5'
 * '<S70>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn5LPress'
 * '<S71>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn5SPress'
 * '<S72>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn6'
 * '<S73>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn7'
 * '<S74>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn8'
 * '<S75>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_Btn9'
 * '<S76>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_ErrorLoc'
 * '<S77>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_ErrorType'
 * '<S78>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/in_IN_NodeMFL.MFL_BtnInfo.MFL_BtnInfo_MsgCounter'
 * '<S79>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_LIN_01.LinNetworkRequest1'
 * '<S80>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_LIN_01.ScheduleTable'
 * '<S81>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_LinSlave.SetFrameLss1B'
 * '<S82>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_LinSlave.SetFrameMlfB'
 * '<S83>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_LinSlave.WakeupRequest'
 * '<S84>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_PCAN.Tx_Acc.Lout_Sts.BatteryVoltage'
 * '<S85>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_PCAN.Tx_Acc.Lout_Sts.Button_KL15'
 * '<S86>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_PCAN.Tx_Acc.Lout_Sts.MessageEnable'
 * '<S87>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.BatteryVoltage'
 * '<S88>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Button_KL15'
 * '<S89>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Voltage_Normal'
 * '<S90>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Voltage_OV1'
 * '<S91>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Voltage_OV2'
 * '<S92>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Voltage_UV1'
 * '<S93>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_LinControl/out_OUT_Tester_1.BSG_STATUS.Voltage_UV2'
 * '<S94>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/in_DIAG_TSUD.ShaftSpeed_DIAG'
 * '<S95>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/in_DIAG_TSUD.VehicleSpeed_DIAG'
 * '<S96>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/in_INOUT_RAMDevice.boSystemWake'
 * '<S97>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/in_IN_TSUD.ShaftSpeed'
 * '<S98>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/in_IN_TSUD.VehicleSpeed'
 * '<S99>'  : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_PCAN.Tx_Tsu.TSU_Sts.MessageEnable'
 * '<S100>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_PCAN.Tx_Tsu.TSU_Sts.Speed_Shaft'
 * '<S101>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_PCAN.Tx_Tsu.TSU_Sts.Speed_Shaft_DIAG'
 * '<S102>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_PCAN.Tx_Tsu.TSU_Sts.Speed_Vehicle'
 * '<S103>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_PCAN.Tx_Tsu.TSU_Sts.Speed_Vehicle_DIAG'
 * '<S104>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_TSUD.DeviceEnable'
 * '<S105>' : 'APP_DevicesControl/Model/APP_DevicesControl_/SUB_TsuControl/out_OUT_TSUD.SetDiagWriteOdoResponse'
 */

/*-
 * Requirements for '<Root>': APP_DevicesControl_
 */
#endif                                 /* RTW_HEADER_APP_DevicesControl__h_ */

/***************************************************************************
 * EOF: APP_DevicesControl_.h
 ***************************************************************************/
