/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_IOControl__data.c
 *
 * Description  : Source-File for MBDS model APP_IOControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.2
 *                Created by       : Marcio Kopke (uid96494) on Tue Dec 22 10:16:48 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_IOControl_.h"
#include "APP_IOControl__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Invariant block signals (default storage) */
const ConstB_APP_IOControl_ APP_IOControl__ConstB =
{
  /* Start of '<S981>/LoopOverBits' */
  {
    2U,                                /* '<S985>/Width' */

    {
      1, 1
    }                                  /* '<S985>/DataType' */
  }
  ,

  /* End of '<S981>/LoopOverBits' */

  /* Start of '<S974>/LoopOverBits' */
  {
    2U,                                /* '<S978>/Width' */

    {
      1, 1
    }                                  /* '<S978>/DataType' */
  }
  ,

  /* End of '<S974>/LoopOverBits' */

  /* Start of '<S967>/LoopOverBits' */
  {
    2U,                                /* '<S971>/Width' */

    {
      1, 1
    }                                  /* '<S971>/DataType' */
  }
  ,

  /* End of '<S967>/LoopOverBits' */

  /* Start of '<S960>/LoopOverBits' */
  {
    2U,                                /* '<S964>/Width' */

    {
      1, 1
    }                                  /* '<S964>/DataType' */
  }
  ,

  /* End of '<S960>/LoopOverBits' */

  /* Start of '<S953>/LoopOverBits' */
  {
    2U,                                /* '<S957>/Width' */

    {
      1, 1
    }                                  /* '<S957>/DataType' */
  }
  ,

  /* End of '<S953>/LoopOverBits' */

  /* Start of '<S946>/LoopOverBits' */
  {
    2U,                                /* '<S950>/Width' */

    {
      1, 1
    }                                  /* '<S950>/DataType' */
  }
  ,

  /* End of '<S946>/LoopOverBits' */

  /* Start of '<S939>/LoopOverBits' */
  {
    2U,                                /* '<S943>/Width' */

    {
      1, 1
    }                                  /* '<S943>/DataType' */
  }
  ,

  /* End of '<S939>/LoopOverBits' */

  /* Start of '<S932>/LoopOverBits' */
  {
    2U,                                /* '<S936>/Width' */

    {
      1, 1
    }                                  /* '<S936>/DataType' */
  }
  ,

  /* End of '<S932>/LoopOverBits' */

  /* Start of '<S925>/LoopOverBits' */
  {
    2U,                                /* '<S929>/Width' */

    {
      1, 1
    }                                  /* '<S929>/DataType' */
  }
  ,

  /* End of '<S925>/LoopOverBits' */

  /* Start of '<S790>/LoopOverBits' */
  {
    2U,                                /* '<S794>/Width' */

    {
      1, 1
    }                                  /* '<S794>/DataType' */
  }
  ,

  /* End of '<S790>/LoopOverBits' */

  /* Start of '<S783>/LoopOverBits' */
  {
    2U,                                /* '<S787>/Width' */

    {
      1, 1
    }                                  /* '<S787>/DataType' */
  }
  ,

  /* End of '<S783>/LoopOverBits' */

  /* Start of '<S776>/LoopOverBits' */
  {
    2U,                                /* '<S780>/Width' */

    {
      1, 1
    }                                  /* '<S780>/DataType' */
  }
  ,

  /* End of '<S776>/LoopOverBits' */

  /* Start of '<S769>/LoopOverBits' */
  {
    2U,                                /* '<S773>/Width' */

    {
      1, 1
    }                                  /* '<S773>/DataType' */
  }
  ,

  /* End of '<S769>/LoopOverBits' */

  /* Start of '<S762>/LoopOverBits' */
  {
    2U,                                /* '<S766>/Width' */

    {
      1, 1
    }                                  /* '<S766>/DataType' */
  }
  ,

  /* End of '<S762>/LoopOverBits' */

  /* Start of '<S755>/LoopOverBits' */
  {
    2U,                                /* '<S759>/Width' */

    {
      1, 1
    }                                  /* '<S759>/DataType' */
  }
  ,

  /* End of '<S755>/LoopOverBits' */

  /* Start of '<S748>/LoopOverBits' */
  {
    2U,                                /* '<S752>/Width' */

    {
      1, 1
    }                                  /* '<S752>/DataType' */
  }
  ,

  /* End of '<S748>/LoopOverBits' */

  /* Start of '<S741>/LoopOverBits' */
  {
    2U,                                /* '<S745>/Width' */

    {
      1, 1
    }                                  /* '<S745>/DataType' */
  }
  ,

  /* End of '<S741>/LoopOverBits' */

  /* Start of '<S734>/LoopOverBits' */
  {
    2U,                                /* '<S738>/Width' */

    {
      1, 1
    }                                  /* '<S738>/DataType' */
  }
  ,

  /* End of '<S734>/LoopOverBits' */

  /* Start of '<S727>/LoopOverBits' */
  {
    2U,                                /* '<S731>/Width' */

    {
      1, 1
    }                                  /* '<S731>/DataType' */
  }
  ,

  /* End of '<S727>/LoopOverBits' */

  /* Start of '<S720>/LoopOverBits' */
  {
    2U,                                /* '<S724>/Width' */

    {
      1, 1
    }                                  /* '<S724>/DataType' */
  }
  ,

  /* End of '<S720>/LoopOverBits' */

  /* Start of '<S713>/LoopOverBits' */
  {
    2U,                                /* '<S717>/Width' */

    {
      1, 1
    }                                  /* '<S717>/DataType' */
  }
  ,

  /* End of '<S713>/LoopOverBits' */

  /* Start of '<S706>/LoopOverBits' */
  {
    2U,                                /* '<S710>/Width' */

    {
      1, 1
    }                                  /* '<S710>/DataType' */
  }
  ,

  /* End of '<S706>/LoopOverBits' */

  /* Start of '<S699>/LoopOverBits' */
  {
    2U,                                /* '<S703>/Width' */

    {
      1, 1
    }                                  /* '<S703>/DataType' */
  }
  ,

  /* End of '<S699>/LoopOverBits' */

  /* Start of '<S692>/LoopOverBits' */
  {
    2U,                                /* '<S696>/Width' */

    {
      1, 1
    }                                  /* '<S696>/DataType' */
  }
  ,

  /* End of '<S692>/LoopOverBits' */

  /* Start of '<S685>/LoopOverBits' */
  {
    2U,                                /* '<S689>/Width' */

    {
      1, 1
    }                                  /* '<S689>/DataType' */
  }
  ,

  /* End of '<S685>/LoopOverBits' */

  /* Start of '<S678>/LoopOverBits' */
  {
    2U,                                /* '<S682>/Width' */

    {
      1, 1
    }                                  /* '<S682>/DataType' */
  }
  ,

  /* End of '<S678>/LoopOverBits' */

  /* Start of '<S671>/LoopOverBits' */
  {
    2U,                                /* '<S675>/Width' */

    {
      1, 1
    }                                  /* '<S675>/DataType' */
  }
  /* End of '<S671>/LoopOverBits' */
};

/* Constant parameters (default storage) */
const ConstP_APP_IOControl_ APP_IOControl__ConstP =
{
  /* Pooled Parameter (Expression: )
   * Referenced by:
   *   '<S671>/SEL'
   *   '<S678>/SEL'
   *   '<S685>/SEL'
   *   '<S692>/SEL'
   *   '<S699>/SEL'
   *   '<S706>/SEL'
   *   '<S713>/SEL'
   *   '<S720>/SEL'
   *   '<S727>/SEL'
   *   '<S734>/SEL'
   *   '<S741>/SEL'
   *   '<S748>/SEL'
   *   '<S755>/SEL'
   *   '<S762>/SEL'
   *   '<S769>/SEL'
   *   '<S776>/SEL'
   *   '<S783>/SEL'
   *   '<S790>/SEL'
   *   '<S925>/SEL'
   *   '<S932>/SEL'
   *   '<S939>/SEL'
   *   '<S946>/SEL'
   *   '<S953>/SEL'
   *   '<S960>/SEL'
   *   '<S967>/SEL'
   *   '<S974>/SEL'
   *   '<S981>/SEL'
   */
  {
    7U, 12U
  }
};

/***************************************************************************
 * EOF: APP_IOControl__data.c
 ***************************************************************************/
