/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_MyApplicationT6__private.h
 *
 * Description  : Header file for MBDS model APP_MyApplicationT6_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.5
 *                Created by       : Udo Kaiser (uidf0608) on Tue Jun 16 06:25:40 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_MyApplicationT6__private_h_
#define RTW_HEADER_APP_MyApplicationT6__private_h_
#include "rtwtypes.h"

/* Includes for objects with custom storage classes. */
#include "ks32_io.h"

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/
#endif                                 /* RTW_HEADER_APP_MyApplicationT6__private_h_ */

/***************************************************************************
 * EOF: APP_MyApplicationT6__private.h
 ***************************************************************************/
