/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_ExpControl__private.h
 *
 * Description  : Header file for MBDS model APP_ExpControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.2
 *                Created by       : Marcio Kopke (uid96494) on Tue Dec 29 10:12:00 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_ExpControl__private_h_
#define RTW_HEADER_APP_ExpControl__private_h_
#include "rtwtypes.h"
#include "APP_ExpControl_.h"

/* Includes for objects with custom storage classes. */
#include "ks32_io.h"

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/
extern void APP_ExpControl__dp(DW_FullHBridgeCtrl_APP_ExpContr *localDW);
extern void APP_ExpControl__a5(boolean_T rtu_bo_UpRqst, boolean_T
  rtu_bo_DownRqst, uint16_T rtu_u16_HB1SideDiag, uint16_T rtu_u16_HB2SideDiag,
  uint16_T rtu_u16_BrakeTime, uint16_T rtu_u16_OpenLoadDetectTime, uint16_T
  rtu_u16_MaxActivationTime, uint16_T rtu_u16_OpenLoadIntervalTime, int8_T
  rtu_i8_HB1SideSimuVal, int8_T rtu_i8_HB2SideSimuVal, boolean_T
  rtu_bo_OpenLoadDetectSimuVal, boolean_T rtu_bo_WorkingMode,
  DW_FullHBridgeCtrl_APP_ExpContr *localDW);
extern void APP_ExpControl__jz(DW_TrailerDetection_APP_ExpCont *localDW);
extern void APP_ExpControl__ar(boolean_T rtu_bo_OutRqst, uint8_T
  rtu_u8_TdTimeout, DW_TrailerDetection_APP_ExpCont *localDW);

#endif                                 /* RTW_HEADER_APP_ExpControl__private_h_ */

/***************************************************************************
 * EOF: APP_ExpControl__private.h
 ***************************************************************************/
