/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_CanInterface_.c
 *
 * Description  : Source-File for MBDS model APP_CanInterface_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.3
 *                Created by       : Marcio Kopke (uid96494) on Thu Dec 31 12:59:37 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_CanInterface_.h"
#include "APP_CanInterface__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Model step function */
void APP_CanInterface__step(void)
{
  /* DataStoreWrite: '<S5>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_ACAN_MessageForwardingEnable_002356 = true;

  /* DataStoreWrite: '<S6>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_DCAN_MessageForwardingEnable_001337 = true;

  /* DataStoreWrite: '<S7>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_DRCAN_MessageForwardingEnable_001335 = true;

  /* DataStoreWrite: '<S8>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_FMSCAN_MessageForwardingEnable_001336 = true;

  /* DataStoreWrite: '<S9>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_HCAN_MessageForwardingEnable_001340 = true;

  /* DataStoreWrite: '<S10>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_ICAN_MessageForwardingEnable_001342 = true;

  /* DataStoreWrite: '<S11>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant'
   */
  OUT_PCAN_MessageForwardingEnable_001347 = true;

  /* DataStoreWrite: '<S57>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant'
   */
  OUT_PCAN_DM1_10_MessageEnable_002229 = true;

  /* DataStoreWrite: '<S58>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant1'
   */
  OUT_PCAN_GenericDM1TxMessage_DeviceEnable_002236 = true;

  /* DataStoreWrite: '<S36>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame1_002241 = 0U;

  /* DataStoreWrite: '<S37>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame10_002270 = 0U;

  /* DataStoreWrite: '<S38>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame2_002253 = 0U;

  /* DataStoreWrite: '<S39>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame3_002254 = 0U;

  /* DataStoreWrite: '<S40>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame4_002255 = 0U;

  /* DataStoreWrite: '<S41>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame5_002256 = 0U;

  /* DataStoreWrite: '<S42>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame6_002266 = 0U;

  /* DataStoreWrite: '<S43>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame7_002267 = 0U;

  /* DataStoreWrite: '<S44>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame8_002268 = 0U;

  /* DataStoreWrite: '<S45>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant2'
   */
  OUT_DEMDiagnosticEventManager_FreezeFrame9_002269 = 0U;

  /* DataStoreWrite: '<S24>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant3'
   */
  OUT_DEMDiagnosticEventManager_DateAndTime_002242 = 0U;

  /* DataStoreWrite: '<S25>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant3'
   */
  OUT_DEMDiagnosticEventManager_Distance_002243 = 0U;

  /* DataStoreWrite: '<S46>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant4'
   */
  OUT_DEMDiagnosticEventManager_OperationCycle_002235 = true;

  /* DataStoreWrite: '<S26>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition00_002239 = false;

  /* DataStoreWrite: '<S27>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition01_002245 = false;

  /* DataStoreWrite: '<S28>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition02_002246 = false;

  /* DataStoreWrite: '<S29>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition03_002247 = false;

  /* DataStoreWrite: '<S30>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition04_002248 = false;

  /* DataStoreWrite: '<S31>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition05_002249 = false;

  /* DataStoreWrite: '<S32>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition06_002250 = false;

  /* DataStoreWrite: '<S33>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition07_002251 = false;

  /* DataStoreWrite: '<S34>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition08_002252 = false;

  /* DataStoreWrite: '<S35>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant5'
   */
  OUT_DEMDiagnosticEventManager_EnableCondition09_002244 = false;

  /* DataStoreWrite: '<S47>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition00_002240 = false;

  /* DataStoreWrite: '<S48>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition01_002258 = false;

  /* DataStoreWrite: '<S49>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition02_002259 = false;

  /* DataStoreWrite: '<S50>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition03_002260 = false;

  /* DataStoreWrite: '<S51>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition04_002261 = false;

  /* DataStoreWrite: '<S52>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition05_002262 = false;

  /* DataStoreWrite: '<S53>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition06_002263 = false;

  /* DataStoreWrite: '<S54>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition07_002264 = false;

  /* DataStoreWrite: '<S55>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition08_002265 = false;

  /* DataStoreWrite: '<S56>/DataStoreMemory' incorporates:
   *  Constant: '<S3>/Constant6'
   */
  OUT_DEMDiagnosticEventManager_StorageCondition09_002257 = false;

  /* DataTypeConversion: '<S3>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S13>/DataStoreMemory'
   *  DataStoreWrite: '<S23>/DataStoreMemory'
   */
  OUT_DEMDiagnosticEventManager_DEMList_DTC_01_002237 = (uint8_T)
    (IN_DM1_10_Filter_boFilter1_002234 ? ((uint8_T)1) : ((uint8_T)0));

  /* DataStoreWrite: '<S60>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_00000501_MessageEnable_001327 = true;

  /* DataStoreWrite: '<S61>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_00000502_MessageEnable_001328 = true;

  /* DataStoreWrite: '<S62>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_00000503_MessageEnable_001329 = true;

  /* DataStoreWrite: '<S63>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_00000504_MessageEnable_001330 = true;

  /* DataStoreWrite: '<S64>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_00000FF1_MessageEnable_001331 = true;

  /* DataStoreWrite: '<S65>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_18DA17F0_MessageEnable_001332 = true;

  /* DataStoreWrite: '<S66>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_18DA17F1_MessageEnable_001333 = true;

  /* DataStoreWrite: '<S67>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant'
   */
  OUT_DCAN_GW_18DAE1F1_MessageEnable_001334 = true;

  /* DataStoreWrite: '<S68>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant1'
   */
  OUT_DRCAN_GW_00000FF6_MessageEnable_001338 = true;

  /* DataStoreWrite: '<S69>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant2'
   */
  OUT_FMSCAN_GW_00000FF5_MessageEnable_001339 = true;

  /* DataStoreWrite: '<S70>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant3'
   */
  OUT_HCAN_GW_00000FF7_MessageEnable_001341 = true;

  /* DataStoreWrite: '<S71>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant4'
   */
  OUT_ICAN_GW_00000600_MessageEnable_001343 = true;

  /* DataStoreWrite: '<S72>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant5'
   */
  OUT_ICAN_GW_00000FF4_MessageEnable_001344 = true;

  /* DataStoreWrite: '<S73>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant5'
   */
  OUT_ICAN_GW_18DAF017_MessageEnable_001345 = true;

  /* DataStoreWrite: '<S74>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant5'
   */
  OUT_ICAN_GW_18DAF117_MessageEnable_001346 = true;

  /* DataStoreWrite: '<S75>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant5'
   */
  OUT_PCAN_GW_00000FF3_MessageEnable_001348 = true;

  /* DataStoreWrite: '<S59>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant6'
   */
  OUT_ACAN_GW_18DAF1E1_MessageEnable_002357 = true;
}

/* Model initialize function */
void APP_CanInterface__initialize(void)
{
  /* (no initialization code required) */
}

/***************************************************************************
 * EOF: APP_CanInterface_.c
 ***************************************************************************/
