/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : rtmodel.h
 *
 * Description  : Header file for MBDS model APP_MyApplicationT3_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.3
 *                Created by       : Udo Kaiser (uidf0608) on Tue Jun 16 06:22:23 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_rtmodel_h_
#define RTW_HEADER_rtmodel_h_
#include "APP_MyApplicationT3_.h"

/* Macros generated for backwards compatibility  */
#ifndef rtmGetErrorStatus
# define rtmGetErrorStatus(rtm)        ((void*) 0)
#endif

#ifndef rtmSetErrorStatus
# define rtmSetErrorStatus(rtm, val)   ((void) 0)
#endif

#ifndef rtmGetStopRequested
# define rtmGetStopRequested(rtm)      ((void*) 0)
#endif

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/
#endif                                 /* RTW_HEADER_rtmodel_h_ */

/***************************************************************************
 * EOF: rtmodel.h
 ***************************************************************************/
