/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_MyApplication_.c
 *
 * Description  : Source-File for MBDS model APP_MyApplication_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.253
 *                Created by       : Udo Kaiser (uidf0608) on Thu Apr 23 04:11:25 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_MyApplication_.h"
#include "APP_MyApplication__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/* Named constants for Chart: '<S25>/Chart' */
#define APP_MyApplic_IN_NO_ACTIVE_CHILD ((uint8_T)0U)
#define APP_MyApplication__IN_SendData ((uint8_T)1U)
#define APP_MyApplication__IN_Wait     ((uint8_T)2U)

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Block signals and states (default storage) */
DW_APP_MyApplication_ APP_MyApplication__DW;

/*
 * Output and update for iterator system:
 *    '<S140>/LoopOverBits'
 *    '<S141>/LoopOverBits'
 *    '<S142>/LoopOverBits'
 *    '<S144>/LoopOverBits'
 *    '<S145>/LoopOverBits'
 *    '<S146>/LoopOverBits'
 */
void APP_MyApplication__du(uint16_T rtu_u, uint8_T rtu_SEL, const
  ConstB_LoopOverBits_APP_MyAppli *localC, DW_LoopOverBits_APP_MyApplicati
  *localDW)
{
  int8_T s204_iter;

  /* Outputs for Iterator SubSystem: '<S140>/LoopOverBits' incorporates:
   *  ForIterator: '<S204>/For Iterator'
   */
  for (s204_iter = 0; s204_iter < ((int8_T)localC->Width); s204_iter++)
  {
    /* Assignment: '<S204>/Assignment1' incorporates:
     *  ArithShift: '<S204>/Shift Arithmetic'
     *  Constant: '<S204>/Constant2'
     *  Constant: '<S204>/Constant3'
     *  RelationalOperator: '<S204>/Relational Operator'
     *  S-Function (sfix_bitop): '<S204>/Bitwise Operator1'
     *  Selector: '<S204>/Selector'
     */
    if (s204_iter == 0)
    {
      localDW->Assignment1 = localC->DataType;
    }

    localDW->Assignment1 = ((((int32_T)rtu_u) & ((int32_T)((uint16_T)((uint32_T)
      (((uint32_T)1) << ((uint64_T)((uint32_T)rtu_SEL))))))) != 0);

    /* End of Assignment: '<S204>/Assignment1' */
  }

  /* End of Outputs for SubSystem: '<S140>/LoopOverBits' */
}

/*
 * System reset for iterator system:
 *    '<S266>/AddDaysForCompleteMonths'
 *    '<S283>/AddDaysForCompleteMonths'
 */
void APP_MyApplication__ig(uint16_T *UnitDelay1_DSTATE)
{
  /* InitializeConditions for UnitDelay: '<S278>/Unit Delay1' */
  *UnitDelay1_DSTATE = 0U;
}

/*
 * Output and update for iterator system:
 *    '<S266>/AddDaysForCompleteMonths'
 *    '<S283>/AddDaysForCompleteMonths'
 */
void APP_MyApplication__hb(uint8_T rtu_u8_Month, DW_AddDaysForCompleteMonths_APP
  *localDW)
{
  int32_T s278_iter;
  uint16_T UnitDelay1_DSTATE;

  /* Outputs for Iterator SubSystem: '<S266>/AddDaysForCompleteMonths' incorporates:
   *  ForIterator: '<S278>/For Iterator'
   */
  APP_MyApplication__ig(&UnitDelay1_DSTATE);
  for (s278_iter = 0; s278_iter < ((int32_T)rtu_u8_Month); s278_iter++)
  {
    /* Sum: '<S278>/Add2' incorporates:
     *  Constant: '<S278>/Constant1'
     *  Selector: '<S278>/Selector'
     *  UnitDelay: '<S278>/Unit Delay1'
     */
    localDW->Add2 = (uint16_T)(((uint32_T)
      APP_MyApplication__ConstP.pooled31[s278_iter]) + ((uint32_T)
      UnitDelay1_DSTATE));

    /* Update for UnitDelay: '<S278>/Unit Delay1' */
    UnitDelay1_DSTATE = localDW->Add2;
  }

  /* End of Outputs for SubSystem: '<S266>/AddDaysForCompleteMonths' */
}

/* Model step function */
void APP_MyApplication__step(void)
{
  boolean_T rtb_LogicalOperator1;
  uint8_T rtb_DataTypeConversion_i4;
  uint16_T rtb_Product_fj;
  uint32_T rtb_Product1;
  uint16_T rtb_Add_fg;
  uint16_T rtb_Product_ar;
  uint16_T rtb_DataTypeConversion1_fz;
  uint8_T rtb_u8_Month;
  boolean_T rtb_RelationalOperator_o0;
  uint32_T rtb_Divide;
  uint32_T rtb_Divide_cy;
  uint32_T rtb_Divide_c5;
  int8_T s301_iter;
  boolean_T rtb_RelationalOperator1_os;
  int32_T i;
  uint64_T tmp;
  uint8_T tmp_0;

  /* Logic: '<S281>/Logical Operator1' incorporates:
   *  Constant: '<S281>/Constant1'
   *  Constant: '<S281>/Constant2'
   *  DataStoreRead: '<S248>/DataStoreMemory'
   *  DataStoreRead: '<S249>/DataStoreMemory'
   *  RelationalOperator: '<S286>/Relational Operator2'
   *  RelationalOperator: '<S288>/Relational Operator'
   */
  rtb_LogicalOperator1 = ((((((((int32_T)STIMD_Alarm_usiSeconds_000630) <= 59) &&
    (((int32_T)STIMD_Alarm_usiMinutes_000628) <= 59)) &&
    (APP_MyApplication__ConstB.RelationalOperator3)) &&
    (APP_MyApplication__ConstB.LogicalOperator1_bh)) &&
    (APP_MyApplication__ConstB.LogicalOperator)) &&
    (APP_MyApplication__ConstB.RelationalOperator_df));

  /* Switch: '<S281>/Switch' incorporates:
   *  Constant: '<S281>/Constant5'
   */
  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    /* Switch: '<S281>/Switch1' incorporates:
     *  Constant: '<S12>/Constant6'
     *  Constant: '<S281>/Constant4'
     */
    if (rtb_LogicalOperator1)
    {
      rtb_u8_Month = 12U;
    }
    else
    {
      rtb_u8_Month = 1U;
    }
  }
  else
  {
    rtb_u8_Month = 12U;
  }

  /* Outputs for Iterator SubSystem: '<S283>/AddDaysForCompleteMonths' */
  APP_MyApplication__hb(rtb_u8_Month,
                        &APP_MyApplication__DW.AddDaysForCompleteMonths_bc);

  /* End of Outputs for SubSystem: '<S283>/AddDaysForCompleteMonths' */

  /* Switch: '<S281>/Switch' incorporates:
   *  Constant: '<S281>/Constant'
   */
  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    /* Switch: '<S281>/Switch1' incorporates:
     *  Constant: '<S12>/Constant5'
     *  Constant: '<S281>/Constant9'
     */
    if (rtb_LogicalOperator1)
    {
      rtb_Add_fg = 2021U;
    }
    else
    {
      rtb_Add_fg = 1970U;
    }
  }
  else
  {
    rtb_Add_fg = 2099U;
  }

  /* Product: '<S296>/Product' incorporates:
   *  Constant: '<S296>/Constant'
   *  Sum: '<S296>/Add'
   */
  rtb_Product_ar = (uint16_T)(((uint32_T)((int32_T)(((int32_T)rtb_Add_fg) - 1970)))
    * 365U);

  /* Product: '<S296>/Divide' incorporates:
   *  Constant: '<S296>/Constant2'
   *  Sum: '<S296>/Subtract'
   */
  rtb_DataTypeConversion1_fz = (uint16_T)(((uint32_T)((int32_T)(((int32_T)
    rtb_Add_fg) - 1968))) >> ((uint64_T)2));

  /* Sum: '<S297>/Subtract' incorporates:
   *  Constant: '<S297>/Constant2'
   */
  rtb_Add_fg = (uint16_T)((int32_T)(((int32_T)rtb_Add_fg) - 1968));

  /* Math: '<S297>/Math Function' */
  rtb_Add_fg = (uint16_T)((int32_T)(((int32_T)rtb_Add_fg) % 4));

  /* Switch: '<S281>/Switch' incorporates:
   *  Constant: '<S12>/Constant1'
   *  Constant: '<S281>/Constant10'
   *  Switch: '<S281>/Switch1'
   */
  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    rtb_DataTypeConversion_i4 = 1U;
  }
  else
  {
    rtb_DataTypeConversion_i4 = 31U;
  }

  /* Sum: '<S283>/Subtract2' incorporates:
   *  Constant: '<S294>/Constant5'
   *  Constant: '<S297>/Constant6'
   *  Constant: '<S297>/Constant7'
   *  Logic: '<S297>/Logical Operator'
   *  RelationalOperator: '<S297>/Relational Operator1'
   *  RelationalOperator: '<S297>/Relational Operator3'
   *  Sum: '<S294>/Subtract4'
   *  Sum: '<S296>/Add1'
   */
  rtb_DataTypeConversion1_fz = (uint16_T)((int32_T)(((((((int32_T)
    rtb_DataTypeConversion_i4) - 1) + ((int32_T)
    APP_MyApplication__DW.AddDaysForCompleteMonths_bc.Add2)) + ((int32_T)
    rtb_Product_ar)) + ((int32_T)rtb_DataTypeConversion1_fz)) - ((int32_T)
    (((((int32_T)rtb_Add_fg) == 0) && (((int32_T)rtb_u8_Month) <= 2)) ? 1 : 0))));

  /* Switch: '<S281>/Switch' incorporates:
   *  Constant: '<S281>/Constant1'
   *  Constant: '<S281>/Constant2'
   *  Constant: '<S281>/Constant3'
   */
  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    /* Switch: '<S281>/Switch1' incorporates:
     *  Constant: '<S281>/Constant15'
     *  DataStoreRead: '<S249>/DataStoreMemory'
     */
    if (rtb_LogicalOperator1)
    {
      rtb_DataTypeConversion_i4 = STIMD_Alarm_usiSeconds_000630;
    }
    else
    {
      rtb_DataTypeConversion_i4 = 0U;
    }
  }
  else
  {
    rtb_DataTypeConversion_i4 = 59U;
  }

  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    /* Switch: '<S281>/Switch1' incorporates:
     *  Constant: '<S281>/Constant15'
     *  DataStoreRead: '<S248>/DataStoreMemory'
     */
    if (rtb_LogicalOperator1)
    {
      rtb_u8_Month = STIMD_Alarm_usiMinutes_000628;
    }
    else
    {
      rtb_u8_Month = 0U;
    }
  }
  else
  {
    rtb_u8_Month = 59U;
  }

  if (APP_MyApplication__ConstB.RelationalOperator1_a5)
  {
    /* Switch: '<S281>/Switch1' incorporates:
     *  Constant: '<S12>/Constant2'
     *  Constant: '<S281>/Constant15'
     */
    if (rtb_LogicalOperator1)
    {
      tmp_0 = 5U;
    }
    else
    {
      tmp_0 = 0U;
    }
  }
  else
  {
    tmp_0 = 23U;
  }

  /* Sum: '<S282>/Add' incorporates:
   *  Constant: '<S291>/Constant'
   *  DataStoreWrite: '<S252>/DataStoreMemory'
   *  Product: '<S291>/Product'
   *  Product: '<S292>/Product1'
   *  Product: '<S293>/Product'
   */
  AlarmDevices_Alarm_NewAlarmTime_000625 = ((((uint32_T)
    rtb_DataTypeConversion_i4) + ((uint32_T)((uint16_T)(((uint32_T)rtb_u8_Month)
    * 60U)))) + (((uint32_T)tmp_0) * 3600U)) + (((uint32_T)
    rtb_DataTypeConversion1_fz) * 86400U);

  /* Outputs for Iterator SubSystem: '<S266>/AddDaysForCompleteMonths' */
  APP_MyApplication__hb(APP_MyApplication__ConstB.u8_Month_hj,
                        &APP_MyApplication__DW.AddDaysForCompleteMonths);

  /* End of Outputs for SubSystem: '<S266>/AddDaysForCompleteMonths' */

  /* Sum: '<S265>/Add' incorporates:
   *  Constant: '<S274>/Constant'
   *  DataStoreWrite: '<S256>/DataStoreMemory'
   *  Product: '<S274>/Product'
   *  Sum: '<S266>/Subtract2'
   */
  DateandTime_NewSystemTime_000417 = ((((uint32_T)
    APP_MyApplication__ConstB.u8_Seconds_pf) + ((uint32_T)
    APP_MyApplication__ConstB.Product)) + APP_MyApplication__ConstB.Product1) +
    (((uint32_T)((uint16_T)(((((uint16_T)APP_MyApplication__ConstB.Subtract4) +
          APP_MyApplication__DW.AddDaysForCompleteMonths.Add2) +
         APP_MyApplication__ConstB.Add1) -
        (APP_MyApplication__ConstB.LogicalOperator_dr ? ((uint16_T)1) :
         ((uint16_T)0))))) * 86400U);

  /* Switch: '<S633>/Switch1' incorporates:
   *  Constant: '<S1>/Constant'
   *  Constant: '<S630>/Constant'
   *  Constant: '<S631>/Constant1'
   *  Constant: '<S631>/dT'
   *  Logic: '<S633>/Logical Operator'
   *  RelationalOperator: '<S629>/Relational Operator'
   *  RelationalOperator: '<S631>/Relational Operator'
   *  RelationalOperator: '<S631>/Relational Operator1'
   *  Switch: '<S631>/Switch1'
   *  UnitDelay: '<S629>/Unit Delay'
   *  UnitDelay: '<S631>/Unit Delay'
   */
  if ((!APP_MyApplication__DW.UnitDelay_DSTATE_e0) &&
      (APP_MyApplication__DW.UnitDelay_DSTATE <= 0U))
  {
    rtb_Product1 = 5000U;
  }
  else if (APP_MyApplication__DW.UnitDelay_DSTATE > 50U)
  {
    /* Switch: '<S631>/Switch1' incorporates:
     *  Constant: '<S631>/dT'
     *  Sum: '<S631>/Subtract'
     */
    rtb_Product1 = APP_MyApplication__DW.UnitDelay_DSTATE - 50U;
  }
  else
  {
    /* Switch: '<S631>/Switch1' incorporates:
     *  Constant: '<S631>/Constant'
     */
    rtb_Product1 = 0U;
  }

  /* End of Switch: '<S633>/Switch1' */

  /* Logic: '<S18>/Operator' incorporates:
   *  Constant: '<S631>/Constant2'
   *  DataStoreRead: '<S31>/DataStoreMemory'
   *  DataStoreRead: '<S32>/DataStoreMemory'
   *  DataStoreWrite: '<S33>/DataStoreMemory'
   *  RelationalOperator: '<S631>/Relational Operator2'
   */
  OUT_ModelControl_ModelHold_000001 = (((IN_DIG_40_KL58_000210) ||
    (IN_DIG_36_KL15_000216)) || (rtb_Product1 > 0U));

  /* DataStoreWrite: '<S36>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant1'
   */
  OUT_ACAN_TX_Gen_ACAN_TX_01_MessageEnable_000083 = true;

  /* DataStoreWrite: '<S35>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant2'
   */
  ACAN_GenericGatewayMessage_MessageEnable_000549 = true;

  /* DataStoreWrite: '<S37>/DataStoreMemory' incorporates:
   *  Constant: '<S2>/Constant3'
   */
  OUT_ACAN_TX_Gen_ACAN_TX_01_Val1_000085 = 2U;

  /* DataStoreWrite: '<S43>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S42>/DataStoreMemory'
   */
  InertianSensorDevice_AccelerometerSubdevice_DeviceEnabl_000649 =
    STIMD_Accel_Enable_000654;

  /* Sum: '<S4>/Add' incorporates:
   *  Constant: '<S4>/Constant9'
   *  DataStoreRead: '<S46>/DataStoreMemory'
   */
  tmp = ((uint64_T)DCAN_TX_Gen_DGenTx_4_Val1_000272) + 1ULL;
  if (tmp > 4294967295ULL)
  {
    tmp = 4294967295ULL;
  }

  /* DataStoreWrite: '<S52>/DataStoreMemory' incorporates:
   *  Sum: '<S4>/Add'
   */
  DCAN_TX_Gen_DGenTx_4_Val1_000272 = (uint32_T)tmp;

  /* DataStoreWrite: '<S51>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant2'
   */
  DCAN_TX_Gen_DGenTx_4_MessageEnable_000270 = true;

  /* DataStoreWrite: '<S57>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant3'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_Val2_000005 = 2U;

  /* DataStoreWrite: '<S58>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant4'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_Val3_000006 = 3U;

  /* DataStoreWrite: '<S59>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant5'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_Val4_000007 = 4U;

  /* DataStoreWrite: '<S60>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant6'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_Val5_000008 = 1234U;

  /* DataStoreWrite: '<S54>/DataStoreMemory' incorporates:
   *  Constant: '<S4>/Constant7'
   */
  OUT_DCAN_RX_Gen_Test1_MessageEnable_000009 = true;

  /* Logic: '<S44>/Operator' incorporates:
   *  DataStoreRead: '<S47>/DataStoreMemory'
   *  DataStoreWrite: '<S55>/DataStoreMemory'
   *  DataTypeConversion: '<S4>/Data Type Conversion'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_MessageEnable_000002 = (((int32_T)
    IN_DCAN_RX_Gen_Test1_MessageState_000010) == 0);

  /* DataStoreWrite: '<S56>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S48>/DataStoreMemory'
   */
  OUT_DCAN_TX_Gen_GenericTxMessage_Val1_000004 =
    IN_DCAN_RX_Gen_Test1_Val1_000011;

  /* DataStoreWrite: '<S53>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S50>/DataStoreMemory'
   */
  DCAN_TX_Gen_GenericTxMessage_CycleTime_000575 = STIMD_GenTxCycleTime_000576;

  /* Logic: '<S61>/Operator' incorporates:
   *  DataStoreRead: '<S83>/DataStoreMemory'
   *  DataStoreWrite: '<S84>/DataStoreMemory'
   */
  DCAN_GenericDM13RXMessage_DeviceEnable_000363 = STIMD_DM13_enable_000367;

  /* DataStoreWrite: '<S85>/DataStoreMemory' incorporates:
   *  DataStoreWrite: '<S84>/DataStoreMemory'
   */
  PCAN_TX_GEN_PGenTX_3_MessageEnable_000640 =
    DCAN_GenericDM13RXMessage_DeviceEnable_000363;

  /* DataTypeConversion: '<S5>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S62>/DataStoreMemory'
   *  DataStoreWrite: '<S87>/DataStoreMemory'
   */
  PCAN_TX_GEN_PGenTX_3_usi_Val_01_000641 = (uint8_T)(DCAN_BusOffState_000639 ?
    ((uint8_T)1) : ((uint8_T)0));

  /* DataStoreWrite: '<S86>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S66>/DataStoreMemory'
   */
  PCAN_TX_GEN_PGenTX_3_ui_Val_02_000642 =
    DCAN_GenericDM13RXMessage_DeviceState_000362;

  /* DataStoreWrite: '<S94>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S91>/DataStoreMemory'
   */
  DCAN_GenericDM1TxMessage_DeviceEnable_000201 = STIMD_D_DM1TX_000636;

  /* DataStoreWrite: '<S95>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S92>/DataStoreMemory'
   */
  FMSCAN_GenericDM1TxMessage_DeviceEnable_000341 = STIMD_F_DM1TX_000637;

  /* DataStoreWrite: '<S96>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S93>/DataStoreMemory'
   */
  PCAN_GenericDM1TxMessage_DeviceEnable_000339 = STIMD_P_DM1TX_000635;

  /* Logic: '<S97>/Operator' incorporates:
   *  Constant: '<S7>/Constant1'
   *  DataStoreWrite: '<S106>/DataStoreMemory'
   */
  DCAN_GenericDM11RXMessage_DeviceEnable_000397 = true;

  /* Logic: '<S98>/Operator' incorporates:
   *  Constant: '<S7>/Constant2'
   *  DataStoreWrite: '<S107>/DataStoreMemory'
   */
  DCAN_GenericDM2TxMessage_Device_Enable_000393 = true;

  /* Logic: '<S99>/Operator' incorporates:
   *  Constant: '<S7>/Constant3'
   *  DataStoreWrite: '<S108>/DataStoreMemory'
   */
  DCAN_GenericDM3RxMessage_Device_Enable_000395 = true;

  /* DataStoreWrite: '<S127>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S119>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTx_5_ui_Val_02_000645 = PCAN_GenericDM4REQ_DeviceState_000319;

  /* Switch: '<S110>/Switch1' incorporates:
   *  Constant: '<S110>/Constant1'
   *  Constant: '<S8>/Constant'
   *  DataStoreRead: '<S119>/DataStoreMemory'
   *  DataStoreRead: '<S124>/DataStoreMemory'
   *  DataStoreWrite: '<S135>/DataStoreMemory'
   *  RelationalOperator: '<S109>/Operator'
   *  Switch: '<S110>/Switch2'
   *  UnitDelay: '<S110>/Unit Delay'
   */
  if (((int32_T)PCAN_GenericDM4REQ_DeviceState_000319) == 9)
  {
    RAMDevice_DM4RX_BusOff_GeneralError_000647 = true;
  }
  else
  {
    RAMDevice_DM4RX_BusOff_GeneralError_000647 =
      ((!STIMD_DM4RX_RequestDm4_000335) &&
       (APP_MyApplication__DW.UnitDelay_DSTATE_dy));
  }

  /* End of Switch: '<S110>/Switch1' */

  /* DataStoreWrite: '<S134>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S124>/DataStoreMemory'
   */
  PCAN_GenericDM4REQ_RequestDM4_000320 = STIMD_DM4RX_RequestDm4_000335;

  /* DataTypeConversion: '<S8>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S118>/DataStoreMemory'
   *  DataStoreWrite: '<S128>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTx_5_usi_Val_01_000644 = (uint8_T)(PCAN_BusOffState_000638 ?
    ((uint8_T)1) : ((uint8_T)0));

  /* DataStoreWrite: '<S126>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S120>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTx_5_MessageEnable_000643 = STIMD_DM4RX_Device_Enable_000646;

  /* DataStoreWrite: '<S133>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S120>/DataStoreMemory'
   */
  PCAN_GenericDM4REQ_DeviceEnable_000318 = STIMD_DM4RX_Device_Enable_000646;

  /* DataStoreWrite: '<S129>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S121>/DataStoreMemory'
   */
  DM4RXMainDevice_EcuAddress_000321 = STIMD_DM4RX_EcuAddress_000333;

  /* DataStoreWrite: '<S130>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S122>/DataStoreMemory'
   */
  DM4RXMainDevice_NextEntry_000326 = STIMD_DM4RX_Next_000334;

  /* DataStoreWrite: '<S131>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S123>/DataStoreMemory'
   */
  DM4RXMainDevice_PreviousEntry_000329 = STIMD_DM4RX_Previous_000332;

  /* DataStoreWrite: '<S132>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S125>/DataStoreMemory'
   */
  DM4RXMainDevice_SAEJ1939Format_000330 = STIMD_DM4RX_SaeFormat_000442;

  /* DataStoreWrite: '<S138>/DataStoreMemory' incorporates:
   *  Constant: '<S9>/Constant1'
   */
  DRCAN_TX_GEN_DRGenTX_1_Val_1_000302 = 66U;

  /* DataStoreWrite: '<S137>/DataStoreMemory' incorporates:
   *  Constant: '<S9>/Constant3'
   */
  DRCAN_TX_GEN_DRGenTX_1_MessageEnable_000300 = true;

  /* Switch: '<S10>/Switch' incorporates:
   *  Constant: '<S10>/Constant8'
   *  DataStoreRead: '<S162>/DataStoreMemory'
   *  DataStoreRead: '<S163>/DataStoreMemory'
   */
  if (STIMD_DTC_enable_000200)
  {
    rtb_DataTypeConversion1_fz = STIMD_DTC_activation_000199;
  }
  else
  {
    rtb_DataTypeConversion1_fz = 4U;
  }

  /* End of Switch: '<S10>/Switch' */

  /* Outputs for Iterator SubSystem: '<S140>/LoopOverBits' */
  /* Constant: '<S10>/Constant9' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 0,
                        &APP_MyApplication__ConstB.LoopOverBits,
                        &APP_MyApplication__DW.LoopOverBits);

  /* End of Outputs for SubSystem: '<S140>/LoopOverBits' */

  /* Switch: '<S10>/Switch5' incorporates:
   *  DataStoreRead: '<S159>/DataStoreMemory'
   *  DataStoreWrite: '<S164>/DataStoreMemory'
   *  Logic: '<S149>/Operator'
   */
  DEMDiagnosticEventManager_DEMList_DTC_01_01_PF_000192 = (uint8_T)
    (((DigitalInputs_IN_DIG_04_000461) ||
      (APP_MyApplication__DW.LoopOverBits.Assignment1)) ? 1 : 0);

  /* Outputs for Iterator SubSystem: '<S141>/LoopOverBits' */
  /* Constant: '<S10>/Constant28' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 1,
                        &APP_MyApplication__ConstB.LoopOverBits_ag,
                        &APP_MyApplication__DW.LoopOverBits_ag);

  /* End of Outputs for SubSystem: '<S141>/LoopOverBits' */

  /* Switch: '<S10>/Switch4' incorporates:
   *  DataStoreRead: '<S159>/DataStoreMemory'
   *  DataStoreWrite: '<S165>/DataStoreMemory'
   *  Logic: '<S150>/Operator'
   */
  DEMDiagnosticEventManager_DEMList_DTC_02_02_AF_000191 = (uint8_T)
    (((DigitalInputs_IN_DIG_04_000461) ||
      (APP_MyApplication__DW.LoopOverBits_ag.Assignment1)) ? 1 : 0);

  /* Outputs for Iterator SubSystem: '<S142>/LoopOverBits' */
  /* Constant: '<S10>/Constant31' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 2,
                        &APP_MyApplication__ConstB.LoopOverBits_jj,
                        &APP_MyApplication__DW.LoopOverBits_jj);

  /* End of Outputs for SubSystem: '<S142>/LoopOverBits' */

  /* Switch: '<S10>/Switch6' incorporates:
   *  DataStoreWrite: '<S166>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_DEMList_DTC_03_03_RF_000190 = (uint8_T)
    (APP_MyApplication__DW.LoopOverBits_jj.Assignment1 ? ((uint8_T)1) :
     ((uint8_T)0));

  /* Outputs for Iterator SubSystem: '<S144>/LoopOverBits' */
  /* Constant: '<S10>/Constant37' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 4,
                        &APP_MyApplication__ConstB.LoopOverBits_gx,
                        &APP_MyApplication__DW.LoopOverBits_gx);

  /* End of Outputs for SubSystem: '<S144>/LoopOverBits' */

  /* Switch: '<S10>/Switch8' incorporates:
   *  Constant: '<S10>/Constant35'
   *  Constant: '<S10>/Constant36'
   *  DataStoreWrite: '<S168>/DataStoreMemory'
   */
  if (APP_MyApplication__DW.LoopOverBits_gx.Assignment1)
  {
    DEMDiagnosticEventManager_DEMList_DTC_05_05_AllOn_000188 = 3U;
  }
  else
  {
    DEMDiagnosticEventManager_DEMList_DTC_05_05_AllOn_000188 = 2U;
  }

  /* End of Switch: '<S10>/Switch8' */

  /* Outputs for Iterator SubSystem: '<S145>/LoopOverBits' */
  /* Constant: '<S10>/Constant40' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 5,
                        &APP_MyApplication__ConstB.LoopOverBits_c4,
                        &APP_MyApplication__DW.LoopOverBits_c4);

  /* End of Outputs for SubSystem: '<S145>/LoopOverBits' */

  /* Switch: '<S10>/Switch9' incorporates:
   *  DataStoreWrite: '<S169>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_DEMList_DTC_06_06_Loff_AllFla_000187 = (uint8_T)
    (APP_MyApplication__DW.LoopOverBits_c4.Assignment1 ? ((uint8_T)1) :
     ((uint8_T)0));

  /* Outputs for Iterator SubSystem: '<S146>/LoopOverBits' */
  /* Constant: '<S10>/Constant22' */
  APP_MyApplication__du(rtb_DataTypeConversion1_fz, 6,
                        &APP_MyApplication__ConstB.LoopOverBits_i1,
                        &APP_MyApplication__DW.LoopOverBits_i1);

  /* End of Outputs for SubSystem: '<S146>/LoopOverBits' */

  /* Switch: '<S10>/Switch1' incorporates:
   *  DataStoreWrite: '<S170>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_DEMList_DTC_1234_22_000336 = (uint8_T)
    (APP_MyApplication__DW.LoopOverBits_i1.Assignment1 ? ((uint8_T)1) :
     ((uint8_T)0));

  /* DataStoreWrite: '<S171>/DataStoreMemory' incorporates:
   *  DataStoreWrite: '<S170>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_DEMList_DTC_86868_6_000337 =
    DEMDiagnosticEventManager_DEMList_DTC_1234_22_000336;

  /* Chart: '<S25>/Chart' incorporates:
   *  DataStoreRead: '<S639>/DataStoreMemory'
   */
  /* Gateway: APP_MyApplication_/UDS Service/Chart */
  rtb_LogicalOperator1 = APP_MyApplication__DW.boRequest_start;
  APP_MyApplication__DW.boRequest_start =
    UDSServices_RoutineControlService_RoutineCtrl1_StartRou_000615;

  /* During: APP_MyApplication_/UDS Service/Chart */
  if (((uint32_T)APP_MyApplication__DW.is_active_c1_APP_MyApplication_) == 0U)
  {
    /* Entry: APP_MyApplication_/UDS Service/Chart */
    APP_MyApplication__DW.is_active_c1_APP_MyApplication_ = 1U;

    /* Entry Internal: APP_MyApplication_/UDS Service/Chart */
    /* Transition: '<S635>:21' */
    APP_MyApplication__DW.is_c1_APP_MyApplication_ = APP_MyApplication__IN_Wait;

    /* Entry 'Wait': '<S635>:6' */
    APP_MyApplication__DW.u8Response = 120U;
  }
  else if (((uint32_T)APP_MyApplication__DW.is_c1_APP_MyApplication_) ==
           APP_MyApplication__IN_SendData)
  {
    /* During 'SendData': '<S635>:7' */
    /* Transition: '<S635>:19' */
    APP_MyApplication__DW.is_c1_APP_MyApplication_ = APP_MyApplication__IN_Wait;

    /* Entry 'Wait': '<S635>:6' */
    APP_MyApplication__DW.u8Response = 120U;
  }
  else
  {
    /* During 'Wait': '<S635>:6' */
    if ((rtb_LogicalOperator1 != APP_MyApplication__DW.boRequest_start) &&
        (APP_MyApplication__DW.boRequest_start))
    {
      /* Transition: '<S635>:20' */
      APP_MyApplication__DW.is_c1_APP_MyApplication_ =
        APP_MyApplication__IN_SendData;

      /* Entry Internal 'SendData': '<S635>:7' */
      /* Transition: '<S635>:23' */
      /* Transition: '<S635>:11' */
      /* Transition: '<S635>:16' */
      APP_MyApplication__DW.u8Response = 0U;

      /* Transition: '<S635>:17' */
      /* Transition: '<S635>:18' */
    }
  }

  /* End of Chart: '<S25>/Chart' */

  /* DataStoreWrite: '<S645>/DataStoreMemory' */
  RAMDevice_RoutineCtrl_Response_000618 = APP_MyApplication__DW.u8Response;

  /* Switch: '<S636>/Switch1' incorporates:
   *  Constant: '<S636>/Constant'
   *  DataStoreRead: '<S639>/DataStoreMemory'
   *  DataStoreRead: '<S640>/DataStoreMemory'
   *  Switch: '<S636>/Switch2'
   *  UnitDelay: '<S636>/Unit Delay'
   */
  if (UDSServices_RoutineControlService_RoutineCtrl1_StopRout_000616)
  {
    rtb_LogicalOperator1 = false;
  }
  else
  {
    rtb_LogicalOperator1 =
      ((UDSServices_RoutineControlService_RoutineCtrl1_StartRou_000615) ||
       (APP_MyApplication__DW.UnitDelay_DSTATE_jf));
  }

  /* End of Switch: '<S636>/Switch1' */

  /* Switch: '<S25>/Switch5' incorporates:
   *  Constant: '<S25>/Constant3'
   *  Constant: '<S25>/Constant4'
   *  DataStoreWrite: '<S647>/DataStoreMemory'
   */
  if (rtb_LogicalOperator1)
  {
    UDSServices_RoutineControlService_RoutineCtrl1_Response_000614 = 15U;
  }
  else
  {
    UDSServices_RoutineControlService_RoutineCtrl1_Response_000614 = 33U;
  }

  /* End of Switch: '<S25>/Switch5' */

  /* DataStoreWrite: '<S173>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant13'
   */
  DEMDiagnosticEventManager_Distance_000184 = 4211024432U;

  /* Logic: '<S148>/Operator' incorporates:
   *  Constant: '<S10>/Constant19'
   *  DataStoreWrite: '<S174>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_EnableCondition00_000205 = true;

  /* Logic: '<S147>/Operator' incorporates:
   *  Constant: '<S10>/Constant19'
   *  DataStoreWrite: '<S186>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_StorageCondition00_000206 = true;

  /* DataStoreWrite: '<S178>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant2'
   */
  DEMDiagnosticEventManager_FreezeFrame3_000178 = 33U;

  /* DataStoreWrite: '<S182>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant23'
   */
  DEMDiagnosticEventManager_FreezeFrame7_000406 = 7U;

  /* DataStoreWrite: '<S183>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant24'
   */
  DEMDiagnosticEventManager_FreezeFrame8_000407 = 8U;

  /* DataStoreWrite: '<S184>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant25'
   */
  DEMDiagnosticEventManager_FreezeFrame9_000408 = 9U;

  /* DataStoreWrite: '<S176>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant26'
   */
  DEMDiagnosticEventManager_FreezeFrame10_000409 = 10U;

  /* DataStoreWrite: '<S179>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant3'
   */
  DEMDiagnosticEventManager_FreezeFrame4_000179 = 44U;

  /* DataStoreWrite: '<S180>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant4'
   */
  DEMDiagnosticEventManager_FreezeFrame5_000180 = 5U;

  /* DataStoreWrite: '<S172>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant41'
   */
  DEMDiagnosticEventManager_DateAndTime_000182 = 1611153355U;

  /* DataStoreWrite: '<S185>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant5'
   */
  DEMDiagnosticEventManager_OperationCycle_000181 = true;

  /* DataStoreWrite: '<S181>/DataStoreMemory' incorporates:
   *  Constant: '<S10>/Constant6'
   */
  DEMDiagnosticEventManager_FreezeFrame6_000405 = 6U;

  /* Product: '<S203>/Divide' incorporates:
   *  Constant: '<S203>/Constant'
   *  DataStoreRead: '<S158>/DataStoreMemory'
   */
  rtb_Divide = DateandTime_SystemTime_000412 / 60U;

  /* RelationalOperator: '<S187>/Relational Operator' incorporates:
   *  Constant: '<S187>/Constant14'
   *  DataStoreRead: '<S158>/DataStoreMemory'
   */
  rtb_RelationalOperator_o0 = (DateandTime_SystemTime_000412 <= 4102444799U);

  /* Switch: '<S139>/Switch' incorporates:
   *  Constant: '<S139>/Constant9'
   *  Constant: '<S202>/Constant1'
   *  DataTypeConversion: '<S201>/Data Type Conversion'
   *  Math: '<S201>/Math Function'
   *  Product: '<S202>/Divide'
   */
  if (rtb_RelationalOperator_o0)
  {
    rtb_DataTypeConversion_i4 = (uint8_T)((rtb_Divide / 60U) % 24U);
  }
  else
  {
    rtb_DataTypeConversion_i4 = 23U;
  }

  /* DataTypeConversion: '<S10>/Data Type Conversion1' incorporates:
   *  DataStoreWrite: '<S175>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_FreezeFrame1_000176 = rtb_DataTypeConversion_i4;

  /* Switch: '<S139>/Switch' incorporates:
   *  Constant: '<S139>/Constant8'
   *  DataTypeConversion: '<S202>/Data Type Conversion1'
   *  Math: '<S202>/Math Function'
   */
  if (rtb_RelationalOperator_o0)
  {
    rtb_DataTypeConversion_i4 = (uint8_T)(rtb_Divide % 60U);
  }
  else
  {
    rtb_DataTypeConversion_i4 = 59U;
  }

  /* DataTypeConversion: '<S10>/Data Type Conversion' incorporates:
   *  DataStoreWrite: '<S177>/DataStoreMemory'
   */
  DEMDiagnosticEventManager_FreezeFrame2_000177 = rtb_DataTypeConversion_i4;

  /* Switch: '<S12>/Switch' incorporates:
   *  DataStoreRead: '<S241>/DataStoreMemory'
   *  DataStoreRead: '<S244>/DataStoreMemory'
   *  DataStoreRead: '<S251>/DataStoreMemory'
   */
  if (STIMD_TimeSourceSelect_000620)
  {
    rtb_Divide = DateandTime_SystemTime_000412;
  }
  else
  {
    rtb_Divide = DateandTime_LocalTime_000415;
  }

  /* End of Switch: '<S12>/Switch' */

  /* Product: '<S314>/Divide' incorporates:
   *  Constant: '<S314>/Constant'
   */
  rtb_Divide_cy = rtb_Divide / 60U;

  /* Product: '<S313>/Divide' incorporates:
   *  Constant: '<S313>/Constant1'
   */
  rtb_Divide_c5 = rtb_Divide_cy / 60U;

  /* DataTypeConversion: '<S312>/Data Type Conversion1' incorporates:
   *  Constant: '<S312>/Constant'
   *  Product: '<S312>/Divide'
   */
  rtb_DataTypeConversion1_fz = (uint16_T)(rtb_Divide_c5 / 24U);

  /* Product: '<S303>/Divide' */
  rtb_Product_fj = (uint16_T)(((uint32_T)rtb_DataTypeConversion1_fz) / 365U);

  /* Product: '<S303>/Divide1' incorporates:
   *  Constant: '<S303>/Constant'
   *  Sum: '<S303>/Add'
   */
  rtb_Add_fg = (uint16_T)((((uint32_T)rtb_Product_fj) + 1U) >> ((uint64_T)2));

  /* Math: '<S299>/Math Function3' */
  rtb_DataTypeConversion1_fz = (uint16_T)((int32_T)(((int32_T)
    rtb_DataTypeConversion1_fz) % 365));

  /* RelationalOperator: '<S306>/Relational Operator' */
  rtb_RelationalOperator_o0 = (rtb_DataTypeConversion1_fz >= rtb_Add_fg);

  /* Sum: '<S299>/Add3' incorporates:
   *  Constant: '<S299>/Constant2'
   *  Constant: '<S299>/Constant6'
   *  RelationalOperator: '<S299>/Relational Operator1'
   */
  rtb_Product_ar = (uint16_T)((int32_T)((((int32_T)((0 == ((int32_T)
    rtb_Product_fj)) ? 1 : 0)) + ((int32_T)rtb_Product_fj)) - 1));

  /* Switch: '<S304>/Switch' incorporates:
   *  Constant: '<S305>/Constant'
   *  Constant: '<S305>/Constant2'
   *  Math: '<S305>/Math Function'
   *  RelationalOperator: '<S305>/Relational Operator'
   *  Sum: '<S304>/Subtract'
   *  Sum: '<S305>/Add'
   *  Switch: '<S304>/Switch1'
   */
  if (rtb_RelationalOperator_o0)
  {
    /* Sum: '<S304>/Subtract' */
    i = ((int32_T)rtb_DataTypeConversion1_fz) - ((int32_T)rtb_Add_fg);
    if (i < 0)
    {
      i = 0;
    }

    rtb_DataTypeConversion1_fz = (uint16_T)i;
  }
  else if (((int32_T)((uint16_T)((int32_T)(((int32_T)((uint16_T)(((uint32_T)
      rtb_Product_ar) + 2U))) % 4)))) == 0)
  {
    /* Switch: '<S304>/Switch1' incorporates:
     *  Constant: '<S299>/DaysPerNonLeapYear'
     *  Sum: '<S304>/Add'
     *  Sum: '<S304>/Add1'
     */
    rtb_DataTypeConversion1_fz = (uint16_T)(((uint32_T)((int32_T)(((int32_T)
      rtb_DataTypeConversion1_fz) - ((int32_T)rtb_Add_fg)))) + 366U);
  }
  else
  {
    /* Switch: '<S304>/Switch1' incorporates:
     *  Constant: '<S299>/DaysPerNonLeapYear'
     *  Sum: '<S304>/Add1'
     */
    rtb_DataTypeConversion1_fz = (uint16_T)((int32_T)((((int32_T)
      rtb_DataTypeConversion1_fz) - ((int32_T)rtb_Add_fg)) + 365));
  }

  /* End of Switch: '<S304>/Switch' */

  /* Switch: '<S299>/Switch1' */
  if (rtb_RelationalOperator_o0)
  {
  }
  else
  {
    rtb_Product_fj = rtb_Product_ar;
  }

  /* End of Switch: '<S299>/Switch1' */

  /* RelationalOperator: '<S307>/Relational Operator2' incorporates:
   *  Constant: '<S307>/Constant'
   *  Constant: '<S307>/Constant9'
   *  Math: '<S307>/Math Function'
   *  Sum: '<S307>/Add6'
   */
  rtb_RelationalOperator_o0 = (((int32_T)((uint16_T)((int32_T)(((int32_T)
    ((uint16_T)(((uint32_T)rtb_Product_fj) + 2U))) % 4)))) == 0);

  /* Outputs for Iterator SubSystem: '<S236>/ConvertToMonthAndDay' incorporates:
   *  WhileIterator: '<S301>/While Iterator'
   */
  s301_iter = 1;

  /* InitializeConditions for UnitDelay: '<S309>/Unit Delay' */
  rtb_Add_fg = 0U;

  /* InitializeConditions for UnitDelay: '<S301>/Unit Delay1' incorporates:
   *  Constant: '<S236>/Constant'
   *  Sum: '<S236>/Add4'
   *  Switch: '<S236>/Switch'
   */
  rtb_DataTypeConversion_i4 = 1U;
  do
  {
    rtb_Add_fg = (uint16_T)((((uint32_T)((rtb_RelationalOperator_o0 &&
      (s301_iter == 3)) ? 1 : 0)) + ((uint32_T)
      APP_MyApplication__ConstP.pooled29[(uint8_T)((int32_T)(((int32_T)s301_iter)
      - 1))])) + ((uint32_T)rtb_Add_fg));
    rtb_Product_ar = (uint16_T)(rtb_DataTypeConversion1_fz - rtb_Add_fg);
    rtb_RelationalOperator1_os = (rtb_Product_ar >= ((uint16_T)((uint8_T)
      (((uint32_T)APP_MyApplication__ConstP.pooled29[s301_iter]) + ((uint32_T)
      (((s301_iter == 2) && rtb_RelationalOperator_o0) ? 1 : 0))))));
    rtb_DataTypeConversion_i4 = (uint8_T)(((uint32_T)(rtb_RelationalOperator1_os
      ? 1U : 0U)) + ((uint32_T)rtb_DataTypeConversion_i4));
    s301_iter++;
  }
  while (rtb_RelationalOperator1_os && (s301_iter <= 12));

  /* End of Outputs for SubSystem: '<S236>/ConvertToMonthAndDay' */

  /* RelationalOperator: '<S298>/Relational Operator' incorporates:
   *  Constant: '<S298>/Constant14'
   */
  rtb_RelationalOperator_o0 = (rtb_Divide <= 4102444799U);

  /* Switch: '<S236>/Switch' incorporates:
   *  Constant: '<S236>/Constant'
   *  Constant: '<S236>/Constant1'
   *  Constant: '<S236>/Constant10'
   *  Constant: '<S236>/Constant11'
   *  Constant: '<S236>/Constant12'
   *  Constant: '<S236>/Constant7'
   *  Constant: '<S236>/Constant8'
   *  Constant: '<S236>/Constant9'
   *  DataStoreWrite: '<S258>/DataStoreMemory'
   *  DataStoreWrite: '<S259>/DataStoreMemory'
   *  DataStoreWrite: '<S260>/DataStoreMemory'
   *  DataStoreWrite: '<S261>/DataStoreMemory'
   *  DataStoreWrite: '<S262>/DataStoreMemory'
   *  DataStoreWrite: '<S263>/DataStoreMemory'
   *  DataTypeConversion: '<S236>/Data Type Conversion1'
   *  DataTypeConversion: '<S312>/Data Type Conversion'
   *  DataTypeConversion: '<S313>/Data Type Conversion1'
   *  DataTypeConversion: '<S314>/Data Type Conversion'
   *  Math: '<S312>/Math Function'
   *  Math: '<S313>/Math Function'
   *  Math: '<S314>/Math Function'
   *  Sum: '<S236>/Add'
   *  Sum: '<S236>/Add1'
   *  Sum: '<S236>/Add4'
   */
  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Day_000424 = (uint8_T)(((uint32_T)rtb_Product_ar) + 1U);
  }
  else
  {
    RAMDevice_DT_Day_000424 = 31U;
  }

  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Seconds_000426 = (uint8_T)(rtb_Divide % 60U);
  }
  else
  {
    RAMDevice_DT_Seconds_000426 = 59U;
  }

  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Minutes_000425 = (uint8_T)(rtb_Divide_cy % 60U);
  }
  else
  {
    RAMDevice_DT_Minutes_000425 = 59U;
  }

  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Hours_000423 = (uint8_T)(rtb_Divide_c5 % 24U);
  }
  else
  {
    RAMDevice_DT_Hours_000423 = 23U;
  }

  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Year_000421 = (uint16_T)(((uint32_T)rtb_Product_fj) + 1970U);
  }
  else
  {
    RAMDevice_DT_Year_000421 = 2099U;
  }

  if (rtb_RelationalOperator_o0)
  {
    RAMDevice_DT_Month_000422 = rtb_DataTypeConversion_i4;
  }
  else
  {
    RAMDevice_DT_Month_000422 = 12U;
  }

  /* Logic: '<S211>/Operator' incorporates:
   *  DataStoreRead: '<S221>/DataStoreMemory'
   *  DataStoreRead: '<S223>/DataStoreMemory'
   *  DataStoreWrite: '<S230>/DataStoreMemory'
   */
  DtcList_DTCList_f_DTClistEna_000243 = ((STIMD_ListDtcEnable_000255) ||
    (IN_DIG_02_DriverDoor_000215));

  /* DataStoreWrite: '<S229>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S222>/DataStoreMemory'
   */
  DtcList_DTCList_f_DTClistECUaddrMask_000242 = STIMD_ListDtcEcuAddrMask_000254;

  /* DataStoreWrite: '<S231>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S224>/DataStoreMemory'
   */
  DtcList_DTCList_f_DTClistNextEntry_000247 = STIMD_ListDtcNextEntry_000256;

  /* DataStoreWrite: '<S232>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S225>/DataStoreMemory'
   */
  DtcList_DTCList_f_DTClistPrevEntry_000250 = STIMD_ListDtcPrevEntry_000257;

  /* DataStoreWrite: '<S228>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S226>/DataStoreMemory'
   */
  DtcList_DTCList_SelectCANChannel_000269 = STIMD_ListDtcSelectCanChannel_000450;

  /* DataStoreWrite: '<S233>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S227>/DataStoreMemory'
   */
  DtcList_DTCList_f_DTClistStatusMask_000253 = STIMD_ListDtcStatusMask_000258;

  /* DataStoreWrite: '<S254>/DataStoreMemory' incorporates:
   *  Constant: '<S12>/Constant14'
   */
  DateandTime_HourOffset_000416 = 0;

  /* DataStoreWrite: '<S255>/DataStoreMemory' incorporates:
   *  Constant: '<S12>/Constant15'
   */
  DateandTime_MinuteOffset_000419 = 0;

  /* DataStoreWrite: '<S253>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S247>/DataStoreMemory'
   */
  AlarmDevices_Alarm_SetAlarm_000626 = STIMD_Alarm_boSetAlarm_000627;

  /* DataStoreWrite: '<S257>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S250>/DataStoreMemory'
   */
  DateandTime_SetTime_000411 = STIMD_TimeDateSet_000420;

  /* DataStoreRead: '<S383>/DataStoreMemory' */
  rtb_Divide = NVMVariables2_Var1_000438;

  /* DataStoreWrite: '<S402>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S391>/DataStoreMemory'
   */
  NVMVariables2_Var1_000438 = STIMD_EEprom_Value_000435;

  /* DataStoreRead: '<S381>/DataStoreMemory' */
  rtb_Divide_c5 = NVMModelRelatedData_NVMVariables3_Val_4_000540;

  /* DataStoreWrite: '<S401>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S391>/DataStoreMemory'
   */
  NVMModelRelatedData_NVMVariables3_Val_4_000540 = STIMD_EEprom_Value_000435;

  /* Switch: '<S417>/Switch1' incorporates:
   *  Constant: '<S14>/Constant2'
   *  Constant: '<S414>/Constant'
   *  Constant: '<S415>/Constant1'
   *  Constant: '<S415>/dT'
   *  Logic: '<S417>/Logical Operator'
   *  RelationalOperator: '<S413>/Relational Operator'
   *  RelationalOperator: '<S415>/Relational Operator'
   *  RelationalOperator: '<S415>/Relational Operator1'
   *  Switch: '<S415>/Switch1'
   *  UnitDelay: '<S413>/Unit Delay'
   *  UnitDelay: '<S415>/Unit Delay'
   */
  if ((!APP_MyApplication__DW.UnitDelay_DSTATE_ko) &&
      (APP_MyApplication__DW.UnitDelay_DSTATE_ck <= 0U))
  {
    rtb_Divide_cy = 10U;
  }
  else if (APP_MyApplication__DW.UnitDelay_DSTATE_ck > 50U)
  {
    /* Switch: '<S415>/Switch1' incorporates:
     *  Constant: '<S415>/dT'
     *  Sum: '<S415>/Subtract'
     */
    rtb_Divide_cy = APP_MyApplication__DW.UnitDelay_DSTATE_ck - 50U;
  }
  else
  {
    /* Switch: '<S415>/Switch1' incorporates:
     *  Constant: '<S415>/Constant'
     */
    rtb_Divide_cy = 0U;
  }

  /* End of Switch: '<S417>/Switch1' */

  /* Outputs for Enabled SubSystem: '<S14>/EnabledSubsystem2' incorporates:
   *  EnablePort: '<S366>/Enable'
   */
  /* RelationalOperator: '<S415>/Relational Operator2' incorporates:
   *  Constant: '<S415>/Constant2'
   *  Inport: '<S366>/In1'
   */
  if (rtb_Divide_cy > 0U)
  {
    APP_MyApplication__DW.In1 = rtb_Divide_c5;
  }

  /* End of RelationalOperator: '<S415>/Relational Operator2' */
  /* End of Outputs for SubSystem: '<S14>/EnabledSubsystem2' */

  /* DataStoreWrite: '<S404>/DataStoreMemory' */
  RAMDevice_EEprom_Var3_Val4_000541 = APP_MyApplication__DW.In1;

  /* Outputs for Enabled SubSystem: '<S14>/EnabledSubsystem1' incorporates:
   *  EnablePort: '<S365>/Enable'
   */
  /* DataStoreRead: '<S389>/DataStoreMemory' */
  if (STIMD_EEprom_Enable_000433)
  {
    /* DataStoreWrite: '<S406>/DataStoreMemory' incorporates:
     *  DataStoreRead: '<S391>/DataStoreMemory'
     */
    NVMVariables2_Var2_000437 = STIMD_EEprom_Value_000435;

    /* DataStoreWrite: '<S405>/DataStoreMemory' incorporates:
     *  DataStoreRead: '<S390>/DataStoreMemory'
     */
    NVMModelRelatedData_NVMVariables2_StoreVariablesToNVM_000440 =
      STIMD_EEprom_Trigger_000434;
  }

  /* End of DataStoreRead: '<S389>/DataStoreMemory' */
  /* End of Outputs for SubSystem: '<S14>/EnabledSubsystem1' */

  /* Switch: '<S411>/Switch1' incorporates:
   *  Constant: '<S14>/Constant1'
   *  Constant: '<S408>/Constant'
   *  Constant: '<S409>/Constant1'
   *  Constant: '<S409>/dT'
   *  Logic: '<S411>/Logical Operator'
   *  RelationalOperator: '<S407>/Relational Operator'
   *  RelationalOperator: '<S409>/Relational Operator'
   *  RelationalOperator: '<S409>/Relational Operator1'
   *  Switch: '<S409>/Switch1'
   *  UnitDelay: '<S407>/Unit Delay'
   *  UnitDelay: '<S409>/Unit Delay'
   */
  if ((!APP_MyApplication__DW.UnitDelay_DSTATE_ai) &&
      (APP_MyApplication__DW.UnitDelay_DSTATE_pz <= 0U))
  {
    rtb_Divide_c5 = 10U;
  }
  else if (APP_MyApplication__DW.UnitDelay_DSTATE_pz > 50U)
  {
    /* Switch: '<S409>/Switch1' incorporates:
     *  Constant: '<S409>/dT'
     *  Sum: '<S409>/Subtract'
     */
    rtb_Divide_c5 = APP_MyApplication__DW.UnitDelay_DSTATE_pz - 50U;
  }
  else
  {
    /* Switch: '<S409>/Switch1' incorporates:
     *  Constant: '<S409>/Constant'
     */
    rtb_Divide_c5 = 0U;
  }

  /* End of Switch: '<S411>/Switch1' */

  /* Outputs for Enabled SubSystem: '<S14>/EnabledSubsystem' incorporates:
   *  EnablePort: '<S364>/Enable'
   */
  /* RelationalOperator: '<S409>/Relational Operator2' incorporates:
   *  Constant: '<S409>/Constant2'
   *  Inport: '<S364>/In1'
   */
  if (rtb_Divide_c5 > 0U)
  {
    APP_MyApplication__DW.In1_pf = rtb_Divide;
  }

  /* End of RelationalOperator: '<S409>/Relational Operator2' */
  /* End of Outputs for SubSystem: '<S14>/EnabledSubsystem' */

  /* DataStoreWrite: '<S403>/DataStoreMemory' */
  RAMDevice_EEprom_Value_000436 = APP_MyApplication__DW.In1_pf;

  /* DataStoreWrite: '<S392>/DataStoreMemory' incorporates:
   *  Constant: '<S14>/Constant8'
   */
  DCAN_TX_Gen_DGenTX_2_MessageEnable_000163 = false;

  /* DataStoreWrite: '<S396>/DataStoreMemory' incorporates:
   *  Constant: '<S14>/Constant9'
   */
  DCAN_TX_Gen_DGenTX_3_MessageEnable_000171 = false;

  /* DataTypeConversion: '<S14>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S374>/DataStoreMemory'
   *  DataStoreWrite: '<S394>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_2_Val2_000165 = (uint16_T)
    (NVMModelRelatedData_NVMVariables_Variable_bo_000161 ? ((uint16_T)1) :
     ((uint16_T)0));

  /* DataTypeConversion: '<S14>/Data Type Conversion1' incorporates:
   *  DataStoreRead: '<S370>/DataStoreMemory'
   *  DataStoreWrite: '<S398>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_3_Val2_000173 =
    NVMModelRelatedData_NVMParameter_Variable_00_000168;

  /* DataStoreWrite: '<S397>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S369>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_3_Val1_000172 =
    NVMModelRelatedData_NVMParameter_DeviceState_000167;

  /* DataStoreWrite: '<S399>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S371>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_3_Val3_000174 =
    NVMModelRelatedData_NVMParameter_Variable_01_000169;

  /* DataStoreWrite: '<S400>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S372>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_3_Val4_000175 =
    NVMModelRelatedData_NVMParameter_Variable_02_000170;

  /* DataStoreWrite: '<S393>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S373>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_2_Val1_000164 =
    NVMModelRelatedData_NVMVariables_DeviceState_000160;

  /* DataStoreWrite: '<S395>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S375>/DataStoreMemory'
   */
  DCAN_TX_Gen_DGenTX_2_Val3_000166 =
    NVMModelRelatedData_NVMVariables_Variable_u16_000162;

  /* DataStoreWrite: '<S429>/DataStoreMemory' incorporates:
   *  Constant: '<S15>/Constant1'
   */
  FMSCAN_TX_GEN_FMSGenTX_1_Val_1_000299 = 55U;

  /* DataStoreWrite: '<S427>/DataStoreMemory' incorporates:
   *  Constant: '<S15>/Constant2'
   */
  FMSCAN_GenericDM1RxSA11_MessageEnable_000446 = true;

  /* DataStoreWrite: '<S428>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S426>/DataStoreMemory'
   */
  FMSCAN_TX_GEN_FMSGenTX_1_MessageEnable_000297 = STIMD_FmsCanEnable_000441;

  /* DataStoreWrite: '<S432>/DataStoreMemory' incorporates:
   *  Constant: '<S16>/Constant1'
   */
  HCAN_TX_GEN_HGenTX_1_Val_1_000266 = 1U;

  /* DataStoreWrite: '<S433>/DataStoreMemory' incorporates:
   *  Constant: '<S16>/Constant2'
   */
  HCAN_TX_GEN_HGenTX_1_Val_2_000267 = 2U;

  /* DataStoreWrite: '<S431>/DataStoreMemory' incorporates:
   *  Constant: '<S16>/Constant7'
   */
  HCAN_TX_GEN_HGenTX_1_MessageEnable_000264 = true;

  /* DataStoreWrite: '<S469>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant'
   */
  ICAN_ICANDM1RxSA19_MessageEnable_000154 = true;

  /* DataStoreWrite: '<S470>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant'
   */
  ICAN_ICANDM1RxSAF1_MessageEnable_000138 = true;

  /* DataStoreWrite: '<S472>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant'
   */
  OUT_ICAN_IGenRx_I_Test1_MessageEnable_000086 = true;

  /* DataStoreWrite: '<S473>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant'
   */
  OUT_ICAN_IGenTx_I_Tes1_MessageEnable_000088 = true;

  /* DataStoreWrite: '<S474>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant3'
   */
  OUT_ICAN_IGenTx_I_Tes1_Val_1_000089 = 100U;

  /* DataStoreWrite: '<S471>/DataStoreMemory' incorporates:
   *  Constant: '<S17>/Constant8'
   */
  ICAN_IPGNRX_PGRxMessage_1_Message_Enable_000452 = true;

  /* Switch: '<S19>/Switch' incorporates:
   *  Constant: '<S19>/Constant8'
   *  DataStoreRead: '<S485>/DataStoreMemory'
   *  DataStoreRead: '<S486>/DataStoreMemory'
   *  DataStoreWrite: '<S487>/DataStoreMemory'
   */
  if (STIMD_OUT_enable_000227)
  {
    DigitalOutputPWM_OUT_20_PWM_000220 = STIMD_OUT_value_000226;
  }
  else
  {
    DigitalOutputPWM_OUT_20_PWM_000220 = 0U;
  }

  /* End of Switch: '<S19>/Switch' */

  /* DataTypeConversion: '<S19>/Data Type Conversion' incorporates:
   *  DataStoreWrite: '<S487>/DataStoreMemory'
   *  DataStoreWrite: '<S490>/DataStoreMemory'
   */
  DigitalOutputsSTATIC_OUT_04_000228 = (((int32_T)
    DigitalOutputPWM_OUT_20_PWM_000220) != 0);

  /* DataStoreWrite: '<S492>/DataStoreMemory' incorporates:
   *  DataStoreWrite: '<S490>/DataStoreMemory'
   */
  OUT_DigitalOutputsSTATIC_OUT_01_000081 = DigitalOutputsSTATIC_OUT_04_000228;

  /* Switch: '<S19>/Switch1' incorporates:
   *  Constant: '<S19>/Constant1'
   *  DataStoreRead: '<S484>/DataStoreMemory'
   *  DataStoreRead: '<S485>/DataStoreMemory'
   *  DataStoreWrite: '<S488>/DataStoreMemory'
   */
  if (STIMD_OUT_enable_000227)
  {
    DigitalOutputPWM_OUT_20_TD_START_000224 = STIMD_OUT_TdActivation_000225;
  }
  else
  {
    DigitalOutputPWM_OUT_20_TD_START_000224 = false;
  }

  /* End of Switch: '<S19>/Switch1' */

  /* DataStoreWrite: '<S489>/DataStoreMemory' incorporates:
   *  DataStoreWrite: '<S488>/DataStoreMemory'
   */
  DigitalOutputsSTATIC_OUT_01_TD_START_000219 =
    DigitalOutputPWM_OUT_20_TD_START_000224;

  /* DataStoreWrite: '<S491>/DataStoreMemory' incorporates:
   *  DataStoreWrite: '<S488>/DataStoreMemory'
   */
  DigitalOutputsSTATIC_OUT_04_TD_START_000232 =
    DigitalOutputPWM_OUT_20_TD_START_000224;

  /* DataStoreWrite: '<S538>/DataStoreMemory' incorporates:
   *  Constant: '<S20>/Constant1'
   *  DataStoreRead: '<S525>/DataStoreMemory'
   *  Sum: '<S20>/Add'
   */
  PCAN_TX_GEN_PGenTX_1_Val_1_000261 = (uint8_T)(((uint32_T)
    PCAN_TX_GEN_PGenTX_1_Val_1_000261) + 1U);

  /* DataStoreWrite: '<S539>/DataStoreMemory' incorporates:
   *  Constant: '<S20>/Constant2'
   */
  PCAN_TX_GEN_PGenTX_1_Val_2_000262 = 2U;

  /* DataTypeConversion: '<S20>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S527>/DataStoreMemory'
   *  DataStoreWrite: '<S540>/DataStoreMemory'
   */
  i = STIMD_CanValue_000585;
  if (STIMD_CanValue_000585 < 0)
  {
    i = 0;
  }

  PCAN_TX_GEN_PGenTX_2_Val_1_000578 = (uint32_T)i;

  /* End of DataTypeConversion: '<S20>/Data Type Conversion' */

  /* DataStoreWrite: '<S535>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S528>/DataStoreMemory'
   */
  PCAN_GenericDM1RxSA32_SwitchDtcMode_000596 = STIMD_DM1RX_SwitchDtcMode_000599;

  /* DataStoreWrite: '<S536>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S529>/DataStoreMemory'
   */
  PCAN_GenericDM1RxSA32_SwitchRecMode_000597 = STIMD_DM1RX_SwitchRecMode_000600;

  /* DataStoreWrite: '<S532>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S530>/DataStoreMemory'
   */
  PCAN_GenericDM1RxSA00_MessageEnable_000278 = STIMD_DM1RX_enable_000598;

  /* DataStoreWrite: '<S533>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S530>/DataStoreMemory'
   */
  PCAN_GenericDM1RxSA19_MessageEnable_000286 = STIMD_DM1RX_enable_000598;

  /* DataStoreWrite: '<S534>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S530>/DataStoreMemory'
   */
  PCAN_GenericDM1RxSA32_MessageEnable_000589 = STIMD_DM1RX_enable_000598;

  /* DataStoreWrite: '<S537>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S531>/DataStoreMemory'
   */
  PCAN_TX_GEN_PGenTX_1_MessageEnable_000259 = STIMD_PCanEnable_000497;

  /* DataStoreWrite: '<S577>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant1'
   */
  PCAN_PGNRX_GenericPGRx1_MessageEnable_000519 = true;

  /* DataStoreWrite: '<S578>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant2'
   */
  PCAN_PGNRX_GenericPGRx2_MessageEnable_000522 = true;

  /* DataStoreWrite: '<S579>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant2'
   */
  PCAN_PGNRX_GenericPGRx3_MessageEnable_000526 = true;

  /* DataStoreWrite: '<S588>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant3'
   */
  PCAN_PGNTX_GenericPGTx3_Val1_000552 = 1U;

  /* DataStoreWrite: '<S582>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant4'
   */
  PCAN_PGNTX_GenericPGTx1_Val_1_000503 = 1U;

  /* DataStoreWrite: '<S583>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant5'
   */
  PCAN_PGNTX_GenericPGTx1_Val_2_000504 = 2U;

  /* DataStoreWrite: '<S580>/DataStoreMemory' incorporates:
   *  Constant: '<S21>/Constant6'
   */
  PCAN_PGNRX_GenericPGRx4_MessageEnable_000563 = true;

  /* DataStoreWrite: '<S581>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S541>/DataStoreMemory'
   */
  PCAN_PGNTX_GenericPGTx1_MessageEnable_000500 = DigitalInputs_IN_DIG_06_000463;

  /* DataStoreWrite: '<S587>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S542>/DataStoreMemory'
   */
  PCAN_PGNTX_GenericPGTx3_MessageEnable_000550 = DigitalInputs_IN_DIG_09_000457;

  /* DataStoreWrite: '<S585>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S543>/DataStoreMemory'
   */
  PCAN_PGNTX_GenericPGTx2_MessageEnable_000529 = DigitalInputs_IN_DIG_30_000480;

  /* DataStoreWrite: '<S600>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S599>/DataStoreMemory'
   */
  RAMDevice_TypeDINT_000580 = STIMD_TypeTest_000583;

  /* DataTypeConversion: '<S22>/Data Type Conversion' incorporates:
   *  DataStoreRead: '<S599>/DataStoreMemory'
   *  DataStoreWrite: '<S601>/DataStoreMemory'
   */
  i = STIMD_TypeTest_000583;
  if (STIMD_TypeTest_000583 > 32767)
  {
    i = 32767;
  }
  else
  {
    if (STIMD_TypeTest_000583 < -32768)
    {
      i = -32768;
    }
  }

  RAMDevice_TypeINT_000581 = (int16_T)i;

  /* End of DataTypeConversion: '<S22>/Data Type Conversion' */

  /* DataTypeConversion: '<S22>/Data Type Conversion1' incorporates:
   *  DataStoreRead: '<S599>/DataStoreMemory'
   *  DataStoreWrite: '<S603>/DataStoreMemory'
   */
  i = STIMD_TypeTest_000583;
  if (STIMD_TypeTest_000583 > 127)
  {
    i = 127;
  }
  else
  {
    if (STIMD_TypeTest_000583 < -128)
    {
      i = -128;
    }
  }

  RAMDevice_TypeSINT_000582 = (int8_T)i;

  /* End of DataTypeConversion: '<S22>/Data Type Conversion1' */

  /* DataStoreWrite: '<S602>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S598>/DataStoreMemory'
   */
  RAMDevice_TypeREAL_000586 = STIMD_TypeReal_000587;

  /* DataStoreWrite: '<S624>/DataStoreMemory' incorporates:
   *  Constant: '<S23>/Constant2'
   */
  TSUD_KFactor_000387 = 4000U;

  /* DataStoreWrite: '<S627>/DataStoreMemory' incorporates:
   *  Constant: '<S23>/Constant3'
   */
  TSUD_TripAReset_000388 = false;

  /* DataStoreWrite: '<S628>/DataStoreMemory' incorporates:
   *  Constant: '<S23>/Constant3'
   */
  TSUD_TripBReset_000389 = false;

  /* Switch: '<S23>/Switch' incorporates:
   *  Constant: '<S23>/Constant5'
   *  Constant: '<S23>/Constant6'
   *  DataStoreRead: '<S604>/DataStoreMemory'
   *  DataStoreWrite: '<S626>/DataStoreMemory'
   */
  if (STIMD_TSU_Source_000619)
  {
    TSUD_SourceOfCalculation_000390 = 1U;
  }
  else
  {
    TSUD_SourceOfCalculation_000390 = 4U;
  }

  /* End of Switch: '<S23>/Switch' */

  /* DataStoreWrite: '<S625>/DataStoreMemory' incorporates:
   *  Constant: '<S23>/Constant7'
   */
  TSUD_SetDiagWriteOdoResponse_000386 = 0U;

  /* DataStoreWrite: '<S623>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S605>/DataStoreMemory'
   */
  TSUD_DeviceEnable_000385 = STIMD_TSU_enable_000391;

  /* DataStoreWrite: '<S644>/DataStoreMemory' incorporates:
   *  Constant: '<S25>/Constant'
   */
  RAMDevice_RAMDevice_usint_000611 = 1U;

  /* DataStoreWrite: '<S643>/DataStoreMemory' incorporates:
   *  Constant: '<S25>/Constant1'
   */
  RAMDevice_RAMDevice_uint_000610 = 2U;

  /* DataStoreWrite: '<S642>/DataStoreMemory' incorporates:
   *  Constant: '<S25>/Constant2'
   */
  RAMDevice_RAMDevice_udint_000609 = 3U;

  /* DataStoreWrite: '<S646>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S637>/DataStoreMemory'
   */
  UDSServices_RejectDiagnosticAccess_000608 = DigitalInputs_IN_DIG_39_000487;

  /* DataStoreWrite: '<S167>/DataStoreMemory' */
  DEMDiagnosticEventManager_DEMList_DTC_04_04_MF_000189 = 0U;

  /* DataStoreWrite: '<S584>/DataStoreMemory' */
  for (i = 0; i < 50; i++)
  {
    PCAN_PGNTX_GenericPGTx1_Val_3_000505[(i)] = 0U;
  }

  /* End of DataStoreWrite: '<S584>/DataStoreMemory' */

  /* DataStoreWrite: '<S586>/DataStoreMemory' */
  for (i = 0; i < 20; i++)
  {
    PCAN_PGNTX_GenericPGTx2_ValArray_000531[(i)] = 0U;
  }

  /* End of DataStoreWrite: '<S586>/DataStoreMemory' */

  /* DataStoreWrite: '<S589>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val10_000553 = 0U;

  /* DataStoreWrite: '<S590>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val2_000554 = 0U;

  /* DataStoreWrite: '<S591>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val3_000555 = 0U;

  /* DataStoreWrite: '<S592>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val4_000556 = 0U;

  /* DataStoreWrite: '<S593>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val5_000557 = 0U;

  /* DataStoreWrite: '<S594>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val6_000558 = 0U;

  /* DataStoreWrite: '<S595>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val7_000559 = 0U;

  /* DataStoreWrite: '<S596>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val8_000560 = 0U;

  /* DataStoreWrite: '<S597>/DataStoreMemory' */
  PCAN_PGNTX_GenericPGTx3_Val9_000561 = 0U;

  /* Update for UnitDelay: '<S629>/Unit Delay' incorporates:
   *  Constant: '<S1>/Constant'
   */
  APP_MyApplication__DW.UnitDelay_DSTATE_e0 = true;

  /* Update for UnitDelay: '<S631>/Unit Delay' */
  APP_MyApplication__DW.UnitDelay_DSTATE = rtb_Product1;

  /* Update for UnitDelay: '<S110>/Unit Delay' incorporates:
   *  DataStoreWrite: '<S135>/DataStoreMemory'
   */
  APP_MyApplication__DW.UnitDelay_DSTATE_dy =
    RAMDevice_DM4RX_BusOff_GeneralError_000647;

  /* Update for UnitDelay: '<S636>/Unit Delay' */
  APP_MyApplication__DW.UnitDelay_DSTATE_jf = rtb_LogicalOperator1;

  /* Update for UnitDelay: '<S413>/Unit Delay' incorporates:
   *  Constant: '<S14>/Constant2'
   */
  APP_MyApplication__DW.UnitDelay_DSTATE_ko = true;

  /* Update for UnitDelay: '<S415>/Unit Delay' */
  APP_MyApplication__DW.UnitDelay_DSTATE_ck = rtb_Divide_cy;

  /* Update for UnitDelay: '<S407>/Unit Delay' incorporates:
   *  Constant: '<S14>/Constant1'
   */
  APP_MyApplication__DW.UnitDelay_DSTATE_ai = true;

  /* Update for UnitDelay: '<S409>/Unit Delay' */
  APP_MyApplication__DW.UnitDelay_DSTATE_pz = rtb_Divide_c5;
}

/* Model initialize function */
void APP_MyApplication__initialize(void)
{
  /* Registration code */

  /* states (dwork) */
  (void) memset((void *)&APP_MyApplication__DW, 0,
                sizeof(DW_APP_MyApplication_));

  /* SystemInitialize for Chart: '<S25>/Chart' */
  APP_MyApplication__DW.is_active_c1_APP_MyApplication_ = 0U;
  APP_MyApplication__DW.is_c1_APP_MyApplication_ =
    APP_MyApplic_IN_NO_ACTIVE_CHILD;
  APP_MyApplication__DW.u8Response = 0U;
}

/***************************************************************************
 * EOF: APP_MyApplication_.c
 ***************************************************************************/
