/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_IOControl__types.h
 *
 * Description  : Header file for MBDS model APP_IOControl_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.2
 *                Created by       : Marcio Kopke (uid96494) on Tue Dec 22 10:16:48 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_IOControl__types_h_
#define RTW_HEADER_APP_IOControl__types_h_

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/
#endif                                 /* RTW_HEADER_APP_IOControl__types_h_ */

/***************************************************************************
 * EOF: APP_IOControl__types.h
 ***************************************************************************/
