/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_System_.h
 *
 * Description  : Header file for MBDS model APP_System_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.6
 *                Created by       : Marcio Kopke (uid96494) on Fri Dec 18 16:47:01 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_System__h_
#define RTW_HEADER_APP_System__h_
#include <string.h>
#ifndef APP_System__COMMON_INCLUDES_
# define APP_System__COMMON_INCLUDES_
#define __TMWTYPES__                                             /* Inferred types compatibility mode */
#include "rtwtypes.h"
#endif                                 /* APP_System__COMMON_INCLUDES_ */

#include "APP_System__types.h"

/* Macros for accessing real-time model data structure */

/* Block signals and states (default storage) for system '<Root>' */
typedef struct
{
  uint16_T u16_Timer;                  /* '<S2>/ModelHoldForceTrue' */
  uint8_T is_active_c3_MBDS_Subsystems;/* '<S2>/ModelHoldForceTrue' */
  uint8_T is_c3_MBDS_Subsystems;       /* '<S2>/ModelHoldForceTrue' */
}
DW_APP_System_;

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/

/* Block signals and states (default storage) */
extern DW_APP_System_ APP_System__DW;

/* Model entry point functions */
extern void APP_System__initialize(void);
extern void APP_System__step(void);

/*-
 * These blocks were eliminated from the model due to optimizations:
 *
 * Block '<S5>/DataType' : Eliminate redundant data type conversion
 * Block '<S6>/DataType' : Eliminate redundant data type conversion
 */

/*-
 * The generated code includes comments that allow you to trace directly
 * back to the appropriate location in the model.  The basic format
 * is <system>/block_name, where system is the system number (uniquely
 * assigned by Simulink) and block_name is the name of the block.
 *
 * Note that this particular code originates from a subsystem build,
 * and has its own system numbers different from the parent model.
 * Refer to the system hierarchy for this subsystem below, and use the
 * MATLAB hilite_system command to trace the generated code back
 * to the parent model.  For example,
 *
 * hilite_system('APP_System/Model/APP_System_')    - opens subsystem APP_System/Model/APP_System_
 * hilite_system('APP_System/Model/APP_System_/Kp') - opens and selects block Kp
 *
 * Here is the system hierarchy for this model
 *
 * '<Root>' : 'APP_System/Model'
 * '<S1>'   : 'APP_System/Model/APP_System_'
 * '<S2>'   : 'APP_System/Model/APP_System_/SUB_SystemStates'
 * '<S3>'   : 'APP_System/Model/APP_System_/in_IN_NVM.Parameter.ModelHoldMinTimeAfterPOR'
 * '<S4>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/ModelHoldForceTrue'
 * '<S5>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/NOT'
 * '<S6>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/OR'
 * '<S7>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/in_INOUT_RAMDevice.boSystemWake'
 * '<S8>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_02'
 * '<S9>'   : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_10'
 * '<S10>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_17'
 * '<S11>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_26'
 * '<S12>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_35'
 * '<S13>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_36'
 * '<S14>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/in_IN_DigitalInputs.IN_DIG_40'
 * '<S15>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/out_INOUT_RAMDevice.boSystemWake'
 * '<S16>'  : 'APP_System/Model/APP_System_/SUB_SystemStates/out_OUT_ModelControl.ModelHold'
 */

/*-
 * Requirements for '<Root>': APP_System_
 */
#endif                                 /* RTW_HEADER_APP_System__h_ */

/***************************************************************************
 * EOF: APP_System_.h
 ***************************************************************************/
