/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_System_.c
 *
 * Description  : Source-File for MBDS model APP_System_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.6
 *                Created by       : Marcio Kopke (uid96494) on Fri Dec 18 16:47:01 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_System_.h"
#include "APP_System__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/* Named constants for Chart: '<S2>/ModelHoldForceTrue' */
#define APP_Sy_IN_Release_ModelHoldTrue ((uint8_T)1U)
#define APP_Sys_IN_WakeUp_ModelHoldTrue ((uint8_T)2U)
#define APP_System__IN_NO_ACTIVE_CHILD ((uint8_T)0U)

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Block signals and states (default storage) */
DW_APP_System_ APP_System__DW;

/* Model step function */
void APP_System__step(void)
{
  boolean_T rtb_bo_ModelHold;

  /* Chart: '<S2>/ModelHoldForceTrue' incorporates:
   *  DataStoreRead: '<S3>/DataStoreMemory'
   */
  /* Gateway: SUB_SystemStates/ModelHoldForceTrue */
  /* During: SUB_SystemStates/ModelHoldForceTrue */
  if (((uint32_T)APP_System__DW.is_active_c3_MBDS_Subsystems) == 0U)
  {
    /* Entry: SUB_SystemStates/ModelHoldForceTrue */
    APP_System__DW.is_active_c3_MBDS_Subsystems = 1U;

    /* Entry Internal: SUB_SystemStates/ModelHoldForceTrue */
    /* Transition: '<S4>:6' */
    APP_System__DW.is_c3_MBDS_Subsystems = APP_Sys_IN_WakeUp_ModelHoldTrue;

    /* Entry 'WakeUp_ModelHoldTrue': '<S4>:4' */
    APP_System__DW.u16_Timer = 0U;
    rtb_bo_ModelHold = true;
  }
  else if (((uint32_T)APP_System__DW.is_c3_MBDS_Subsystems) ==
           APP_Sy_IN_Release_ModelHoldTrue)
  {
    rtb_bo_ModelHold = false;

    /* During 'Release_ModelHoldTrue': '<S4>:5' */
  }
  else
  {
    rtb_bo_ModelHold = true;

    /* During 'WakeUp_ModelHoldTrue': '<S4>:4' */
    if (APP_System__DW.u16_Timer >=
        IN_NVM_Parameter_ModelHoldMinTimeAfterPOR_002693)
    {
      /* Transition: '<S4>:15' */
      APP_System__DW.is_c3_MBDS_Subsystems = APP_Sy_IN_Release_ModelHoldTrue;

      /* Entry 'Release_ModelHoldTrue': '<S4>:5' */
      rtb_bo_ModelHold = false;
    }
    else
    {
      APP_System__DW.u16_Timer = (uint16_T)((int32_T)(((int32_T)
        APP_System__DW.u16_Timer) + 1));
    }
  }

  /* End of Chart: '<S2>/ModelHoldForceTrue' */

  /* Logic: '<S6>/Operator' incorporates:
   *  DataStoreRead: '<S10>/DataStoreMemory'
   *  DataStoreRead: '<S11>/DataStoreMemory'
   *  DataStoreRead: '<S12>/DataStoreMemory'
   *  DataStoreRead: '<S13>/DataStoreMemory'
   *  DataStoreRead: '<S14>/DataStoreMemory'
   *  DataStoreRead: '<S8>/DataStoreMemory'
   *  DataStoreRead: '<S9>/DataStoreMemory'
   *  DataStoreWrite: '<S15>/DataStoreMemory'
   *  Logic: '<S5>/Operator'
   */
  INOUT_RAMDevice_boSystemWake_000003 =
    ((((((((IN_DigitalInputs_IN_DIG_02_000035) ||
           (IN_DigitalInputs_IN_DIG_10_000096)) ||
          (!IN_DigitalInputs_IN_DIG_17_000016)) ||
         (IN_DigitalInputs_IN_DIG_26_000034)) ||
        (IN_DigitalInputs_IN_DIG_35_000058)) ||
       (IN_DigitalInputs_IN_DIG_36_000060)) ||
      (IN_DigitalInputs_IN_DIG_40_000068)) || rtb_bo_ModelHold);

  /* DataStoreWrite: '<S16>/DataStoreMemory' incorporates:
   *  DataStoreRead: '<S7>/DataStoreMemory'
   */
  OUT_ModelControl_ModelHold_000001 = INOUT_RAMDevice_boSystemWake_000003;
}

/* Model initialize function */
void APP_System__initialize(void)
{
  /* Registration code */

  /* states (dwork) */
  (void) memset((void *)&APP_System__DW, 0,
                sizeof(DW_APP_System_));

  /* SystemInitialize for Chart: '<S2>/ModelHoldForceTrue' */
  APP_System__DW.is_active_c3_MBDS_Subsystems = 0U;
  APP_System__DW.is_c3_MBDS_Subsystems = APP_System__IN_NO_ACTIVE_CHILD;
  APP_System__DW.u16_Timer = 0U;
}

/***************************************************************************
 * EOF: APP_System_.c
 ***************************************************************************/
