/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_MyApplicationT2_.c
 *
 * Description  : Source-File for MBDS model APP_MyApplicationT2_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_c_template.cgt
 *
 * Model History: Current model version 1.5
 *                Created by       : Udo Kaiser (uidf0608) on Tue Jun 16 06:22:00 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifdef IS_TARGET_CODE

/* Include memory section definitions */
#include "rtdef_mem.h"
#endif

#include "APP_MyApplicationT2_.h"
#include "APP_MyApplicationT2__private.h"

/***************************************************************************
 * FILE LOCAL DEFINITIONS
 ***************************************************************************/

/***************************************************************************
 * GLOBAL DEFINITIONS
 ***************************************************************************/

/* Model step function */
void APP_MyApplicationT2__step(void)
{
  /* (no output/update code required) */
}

/* Model initialize function */
void APP_MyApplicationT2__initialize(void)
{
  /* (no initialization code required) */
}

/***************************************************************************
 * EOF: APP_MyApplicationT2_.c
 ***************************************************************************/
