/***************************************************************************
 * ================== Copyright by Continental Automotive ==================
 ***************************************************************************
 * Title        : APP_MyApplicationT5_.h
 *
 * Description  : Header file for MBDS model APP_MyApplicationT5_
 *
 * Environment  : Generated by MBDS using the Embedded-Coder by the Mathworks.
 *                Simulink-Target            : MBDS
 *                Real-Time Workshop version : 9.0 (R2018b) 24-May-2018
 *                TLC version                : 9.0 (Jan  4 2021)
 *
 * Template Name: MBDS_code_h_template.cgt
 *
 * Model History: Current model version 1.10
 *                Created by       : Udo Kaiser (uidf0608) on Tue Jun 16 06:25:25 2020
 *                Last Modified by :  on
 ***************************************************************************/
/***************************************************************************
 * HEADER-FILES
 ***************************************************************************/
#ifndef RTW_HEADER_APP_MyApplicationT5__h_
#define RTW_HEADER_APP_MyApplicationT5__h_
#ifndef APP_MyApplicationT5__COMMON_INCLUDES_
# define APP_MyApplicationT5__COMMON_INCLUDES_
#define __TMWTYPES__                                             /* Inferred types compatibility mode */
#include "rtwtypes.h"
#endif                                 /* APP_MyApplicationT5__COMMON_INCLUDES_ */

#include "APP_MyApplicationT5__types.h"

/* Macros for accessing real-time model data structure */

/***************************************************************************
 * EXPORT INTERFACE DEFINITIONS AND DECLARATIONS
 ***************************************************************************/

/* Model entry point functions */
extern void APP_MyApplicationT5__initialize(void);
extern void APP_MyApplicationT5__step(void);

/*-
 * The generated code includes comments that allow you to trace directly
 * back to the appropriate location in the model.  The basic format
 * is <system>/block_name, where system is the system number (uniquely
 * assigned by Simulink) and block_name is the name of the block.
 *
 * Note that this particular code originates from a subsystem build,
 * and has its own system numbers different from the parent model.
 * Refer to the system hierarchy for this subsystem below, and use the
 * MATLAB hilite_system command to trace the generated code back
 * to the parent model.  For example,
 *
 * hilite_system('APP_MyApplicationT5/Model/APP_MyApplicationT5_')    - opens subsystem APP_MyApplicationT5/Model/APP_MyApplicationT5_
 * hilite_system('APP_MyApplicationT5/Model/APP_MyApplicationT5_/Kp') - opens and selects block Kp
 *
 * Here is the system hierarchy for this model
 *
 * '<Root>' : 'APP_MyApplicationT5/Model'
 * '<S1>'   : 'APP_MyApplicationT5/Model/APP_MyApplicationT5_'
 * '<S2>'   : 'APP_MyApplicationT5/Model/APP_MyApplicationT5_/in_IN_DigitalInputs.IN_DIG_01'
 */

/*-
 * Requirements for '<Root>': APP_MyApplicationT5_
 */
#endif                                 /* RTW_HEADER_APP_MyApplicationT5__h_ */

/***************************************************************************
 * EOF: APP_MyApplicationT5_.h
 ***************************************************************************/
