@echo off
SET MATLAB=C:\LegacyApp\Matlab18b\R2018b
SET Path=C:\Program Files\MBDS_v0820\MBRT\eBSG_EVO_BTMS\Host\GreenHills;%Path%
"%MATLAB%\bin\win64\gmake" -f SYS_RT_Test_eBSG_BTMS_010001.mk _MBDS_DIR="C:\Program Files\MBDS_v0820" _PROJECT_DIR="C:\Proj\BSG_EVO\TestApp\__eBSG__BTMS\RT_Test_eBSG_BTMS_010001" _PROJECT_NAME=RT_Test_eBSG_BTMS_010001 _RESOURCETYPE=eBSG_EVO_BTMS _ADMINHEADERTYPE="Admin Header 3.0" _SW_STARTADDRESS=0x1A20000 _SW_ENDADDRESS=0x1DCFFFF _TASK_INDEX=0 _OUTPUTMODE=Binary _DEBUGMODE=On _GENERATE_A2L=On _GENERATE_ODX=On
